### ISSUE TITLE
correction function

### ISSUE THREAD

**Issue by zhan1457** [HiFiLES/HiFiLES-solver#100]
Hi,

In your paper (Verification and Validation of HiFiLES: a High-Order LES unstructured solver on multi-GPU platforms) you mention that the solution is made continuous by the correction functions (g_L, g_R, h_L and h_R). However, you have not included the exact expression for these functions. Could you provide any reference to help me understand how the correction function works? Thanks.

Wanjia

**Comment by mlopez14** [comment]
Correct. We cite the work of those before us:

1D and tensor products: Vincent, P., Castonguay, P. & Jameson, A.: "A New Class of High-Order Energy Stable Flux Reconstruction Schemes", Journal of Scientific Computing, DOI 10.1007/s10915-010-9420-z, 17 September 2010, (Also in Vol. 47, Issue 1, pp. 50-72, April 2011).

Triangles: Williams, D. M., Castonguay, P., Vincent, P. E. and Jameson, A.: Energy Stable Flux Reconstruction Schemes for Advection-Diffusion Problems on Triangles, Journal of Computational Physics, DOI: 10.1016/jcp.2013.05.007, Vol. 250, pp. 53-76, October 2013.

Williams, D. M. and Jameson, A.: Energy stable flux reconstruction schemes for advection-diffusion problems on tetrahedra. Journal of Scientific Computing, Vol. 59, Issue 3, pp. 721-759, June 2014.

You can find the pdfs of these (and more) here: http://aero-comlab.stanford.edu/publications.html

**Comment by zhan1457** [comment]
Thank you!
