### ISSUE TITLE
How to estimate the first layer thickness on a wall when using HiFiLES?

### ISSUE THREAD

**Issue by popstar0426** [HiFiLES/HiFiLES-solver#103]
Hi:
  The wall distance is normally required around y+ =1 in DNS or Wall Resolved LES.
   How about the mesh requirement in HiFiLES?
   How to estimate the first layer thicknes on a wall when using HiFiLES?

Best regards!
Yue

**Comment by mlopez14** [comment]
Here is a neat calculator for finding the width of the element closest to the no-slip boundary. 
http://www.pointwise.com/yplus/
This calculator is intended for 2nd order methods, so multiply whatever width this calculator suggests by (p+1)/2, where p is the degree of the polynomial you are using to approximate the solution.

In this way, the first degree of freedom will be at a distance close to y+

**Comment by popstar0426** [comment]
Can HiFiLES solve a flow with Ma =0.025?

Best regards!

**Comment by mlopez14** [comment]
Yes, using the Rusanov flux.

**Comment by popstar0426** [comment]
Hi:

   Using http://www.pointwise.com/yplus/, the first layer thickness could be estimated as 3.7e-5 at Re=60000 with 2nd order method.
   If the 4th order will be used in HiFiLES, the first layer thickness shall be 9.25e-5. 
   Hence, I set the first layer thickness as 9e-5 in my mesh. 
   However, the timestep had to be so small as 1e-8 .
   It will take quite a lot computational resources.

   Now I have a doubt of the SD7003 case (Transitional Flow Over SD7003 airfoil at Ma=0.2 Re=60000) in your paper (AIAA 2011-3229 On the Development of a High-Order, Multi-GPU
Enabled, Compressible Viscous Flow Solver for Mixed Unstructured Grids).
   The hexahedral mesh contains 331,776 cells, for a total 21.2 million DOFs. 
    I do not think I can get a good result as Figure 26 with only 400,000 Runga-Kutta iterations.
    Assume the chord of the airfoil is 1 meter (unit length)
    Because with the time step of 1e-8 (second), the 400,000 iterations only perform a time of 0.004s.
    Such a short time multiply 60 m/s (Ma = 0.2) is only 0.24 meter. 
    In my opinoin, the result in Figure 26 shall be got with two flow (at least) pass through the airfoil.
    
     There is only one posibility, you time step is quite large than 1e-8.
     Then question is: How did you do that?
     Can you tell me the time step of this case?
     If it is possible, cou you share me you mesh and input file?
  
Best regards!
Yue
