### ISSUE TITLE
What is the benefit of using BLAS Lib in HiFiLES?  

### ISSUE THREAD

**Issue by popstar0426** [HiFiLES/HiFiLES-solver#104]
Hi:
   I have a question of using BLAS lib in HiFiLES.
   What is the benefit of using BLAS Lib in HiFiLES?
   Will it speed the calculation?
   Or will it make the simulation more faster?

Best regards!
Yue

**Comment by JacobCrabill** [comment]
BLAS (Basic Linear Algebra Subroutines) is a generic name for any of a number of libraries with similar/identical API calls.  If you've never heard of BLAS before, I highly suggest you do a quick Google search to understand why it's so commonly used, and why it makes numerical linear-algebra routines so much faster.  I would also recommend taking a basic class (or doing some reading) on computer architecture (specifically the CPU cache), as the performance you gain from using BLAS vs. a naive implementation of matrix-matrix / matrix-vector multiplications comes completely from writing code to use the underlying hardware in an intelligent way.
