### ISSUE TITLE
Should I change Fluid Parameters?

### ISSUE THREAD

**Issue by popstar0426** [HiFiLES/HiFiLES-solver#105]
Hi:
  I noticed Fluid Parameters in the input file:
  Fluid Parameters
•gamma: Ratio of specific heats 
◦1.4 by default
•prandtl: Prandtl number 
◦0.72 by defult
•R_gas: Ideal gas constant (J/kg-K) 
◦286.9 by default
•mu_gas: Dynamic viscosity (kg/m-s) 
◦1.827E-05 by default
•S_gas: "S" from Sutherland's Law for viscosity 
◦120 by defult
•T_gas: Temperature of the gas for Sutherland's Law (Kelvin) 
◦291.15 by default
•fix_vis // 0: Sutherland's law, 1: Constant viscosity 
◦0 | Sutherland's Law [default]
◦1 | Constant viscosity
  
   Consider the wing in air with altitude 20km, should I change these parameters for a new simulation?

Best regards!
Yue

--------------------------------------------------------------------------------

**Comment by mlopez14** [comment]
How do the density, dynamic viscosity, and temperature of air change as you go high up in the atmosphere?

**Comment by popstar0426** [comment]
I am not sure the  Sutherland's law works.
May I set Constant viscosity instead?
I can check the air parameters from "Data come from U.S. Standard Atmosphere, 1976" and get the Dynamic viscosity.
I found taht Sutherland's law coefficients in HiFiLES are quite different from them in this website http://www.cfd-online.com/Wiki/Sutherland_law
