### ISSUE TITLE
Something wrong with ATLAS installation in wiki

### ISSUE THREAD

**Issue by popstar0426** [HiFiLES/HiFiLES-solver#106]
Hi:
   I followed the installation step (https://github.com/HiFiLES/HiFiLES-solver/wiki/Installing-ATLAS-in-Ubuntu) to install ATLAS in ubuntu 14.04.
   However, there was something wrong at the ./configure step. My steps are attached below.
 
  airfoil@airfoil-System-Product-Name:~/Desktop/ATLAS_Install$ ls
ATLAS  atlas3.10.2.tar.bz2
airfoil@airfoil-System-Product-Name:~/Desktop/ATLAS_Install$ mkdir /usr/local/atlas
mkdir: cannot create directory ‘/usr/local/atlas’: Permission denied
airfoil@airfoil-System-Product-Name:~/Desktop/ATLAS_Install$ sudo mkdir /usr/local/atlas
[sudo] password for airfoil: 
airfoil@airfoil-System-Product-Name:~/Desktop/ATLAS_Install$ cd /usr/local/atlasairfoil@airfoil-System-Product-Name:/usr/local/atlas$ ~/Desktop/ATLAS_Install/ATLAS/./configure
touch: cannot touch ‘/usr/local/atlas/TstBld973.txt’: Permission denied
rm: cannot remove ‘/usr/local/atlas/TstBld973.txt’: No such file or directory
/home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: 293: /home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: cannot create Makefile: Permission denied
/home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: 294: /home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: cannot create Makefile: Permission denied
/home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: 295: /home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: cannot create Makefile: Permission denied
/home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: 296: /home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: cannot create Makefile: Permission denied
/home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: 297: /home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: cannot create Makefile: Permission denied
/home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: 298: /home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: cannot create Makefile: Permission denied
/home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: 299: /home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: cannot create Makefile: Permission denied
/home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: 306: /home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: cannot create Makefile: Permission denied
/home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: 307: /home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: cannot create Makefile: Permission denied
/home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: 312: /home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: cannot create Makefile: Permission denied
/home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: 313: /home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: cannot create Makefile: Permission denied
/home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: 314: /home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: cannot create Makefile: Permission denied
/home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: 348: /home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: cannot create Makefile: Permission denied
/home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: 350: /home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: cannot create Makefile: Permission denied
cp: cannot create regular file ‘./atlcomp.txt’: Permission denied
make: Makefile: No such file or directory
make: *** No rule to make target `Makefile'.  Stop.
./xconfig -d s /home/airfoil/Desktop/ATLAS_Install/ATLAS/./ -d b /usr/local/atlas 
/bin/sh: 1: ./xconfig: not found
xconfig exited with 127
airfoil@airfoil-System-Product-Name:/usr/local/atlas$ sudo ~/Desktop/ATLAS_Install/ATLAS/./configure
gcc -I/home/airfoil/Desktop/ATLAS_Install/ATLAS/.//CONFIG/include  -g -w -c /home/airfoil/Desktop/ATLAS_Install/ATLAS/.//CONFIG/src/atlconf_misc.c
gcc -I/home/airfoil/Desktop/ATLAS_Install/ATLAS/.//CONFIG/include  -g -w -o xconfig /home/airfoil/Desktop/ATLAS_Install/ATLAS/.//CONFIG/src/config.c atlconf_misc.o 
/tmp/ccUrWCj6.o: In function `ATL_tmpnam':
/home/airfoil/Desktop/ATLAS_Install/ATLAS/.//CONFIG/include/atlas_sys.h:224: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
./xconfig -d s /home/airfoil/Desktop/ATLAS_Install/ATLAS/./ -d b /usr/local/atlas 
probe_OS.o: In function `ATL_tmpnam':
/home/airfoil/Desktop/ATLAS_Install/ATLAS/.//CONFIG/include/atlas_sys.h:224: warning: the use of `tmpnam' is dangerous, better use `mkstemp'

OS configured as Linux (1)
probe_asm.o: In function `ATL_tmpnam':
/home/airfoil/Desktop/ATLAS_Install/ATLAS/.//CONFIG/include/atlas_sys.h:224: warning: the use of `tmpnam' is dangerous, better use `mkstemp'

Assembly configured as GAS_x8664 (2)
probe_vec.o: In function `ATL_tmpnam':
/home/airfoil/Desktop/ATLAS_Install/ATLAS/.//CONFIG/include/atlas_sys.h:224: warning: the use of `tmpnam' is dangerous, better use `mkstemp'

Vector ISA Extension configured as  SSE3 (6,448)
probe_arch.o: In function `ATL_tmpnam':
/home/airfoil/Desktop/ATLAS_Install/ATLAS/.//CONFIG/include/atlas_sys.h:224: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
/tmp/cckawNcV.o: In function `ATL_tmpnam':
/home/airfoil/Desktop/ATLAS_Install/ATLAS/.//CONFIG/include/atlas_sys.h:224: warning: the use of `tmpnam' is dangerous, better use `mkstemp'

Architecture configured as  Corei1 (26)
/tmp/cccw1Dpg.o: In function `ATL_tmpnam':
/home/airfoil/Desktop/ATLAS_Install/ATLAS/.//CONFIG/include/atlas_sys.h:224: warning: the use of `tmpnam' is dangerous, better use `mkstemp'

Clock rate configured as 2801Mhz

Maximum number of threads configured as  8
probe_pmake.o: In function `ATL_tmpnam':
/home/airfoil/Desktop/ATLAS_Install/ATLAS/.//CONFIG/include/atlas_sys.h:224: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
Parallel make command configured as '$(MAKE) -j 8'
Cannot detect CPU throttling.
gcc -I/home/airfoil/Desktop/ATLAS_Install/ATLAS/.//CONFIG/include  -g -w -o xisgcc /home/airfoil/Desktop/ATLAS_Install/ATLAS/.//CONFIG/src/IsGcc.c atlconf_misc.o 
/tmp/ccoZEjGy.o: In function `ATL_tmpnam':
/home/airfoil/Desktop/ATLAS_Install/ATLAS/.//CONFIG/include/atlas_sys.h:224: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
gcc -I/home/airfoil/Desktop/ATLAS_Install/ATLAS/.//CONFIG/include  -g -w -c /home/airfoil/Desktop/ATLAS_Install/ATLAS/.//CONFIG/src/probe_comp.c
gcc -I/home/airfoil/Desktop/ATLAS_Install/ATLAS/.//CONFIG/include  -g -w -o xprobe_comp probe_comp.o atlconf_misc.o 
probe_comp.o: In function `ATL_tmpnam':
/home/airfoil/Desktop/ATLAS_Install/ATLAS/.//CONFIG/include/atlas_sys.h:224: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
rm -f config1.out
make atlas_run atldir=/usr/local/atlas exe=xprobe_comp redir=config1.out \
                args="-v 0 -o atlconf.txt -O 1 -A 26 -Si nof77 0 -V 448   -b 64 -d b /usr/local/atlas"
make[1]: Entering directory `/usr/local/atlas'
cd /usr/local/atlas ; ./xprobe_comp -v 0 -o atlconf.txt -O 1 -A 26 -Si nof77 0 -V 448   -b 64 -d b /usr/local/atlas > config1.out
make[2]: gfortran: Command not found
make[2]: *** [IRunF77Comp] Error 127
make[2]: g77: Command not found
make[2]: *** [IRunF77Comp] Error 127
make[2]: f77: Command not found
make[2]: *** [IRunF77Comp] Error 127

Unable to find usable compiler for F77; abortingMake sure compilers are in your path, and specify good compilers to configure
(see INSTALL.txt or 'configure --help' for details)make[1]: *** [atlas_run] Error 8
make[1]: Leaving directory `/usr/local/atlas'
make: *** [IRun_comp] Error 2
ERROR 512 IN SYSCMND: 'make IRun_comp args="-v 0 -o atlconf.txt -O 1 -A 26 -Si nof77 0 -V 448   -b 64"'
mkdir src bin tune interfaces
cd src ; mkdir testing auxil blas lapack pthreads threads
cd src/blas ; \
           mkdir f77reference reference gemv ger gemm kbmm \
                 level1 level2 level3 pklevel3
cd src/blas/reference ; mkdir level1 level2 level3
cd src/blas/level2 ; mkdir kernel
cd src/blas/pklevel3 ; mkdir gpmm sprk
cd src/blas/level3 ; mkdir rblas kernel
cd src/pthreads ; mkdir blas misc
cd src/pthreads/blas ; mkdir level1 level2 level3
cd src/threads ; mkdir blas lapack
cd src/threads/blas ; mkdir level3 level2
cd tune ; mkdir blas sysinfo lapack threads
cd tune/blas ; mkdir gemm gemv ger level1 level3
cd interfaces ; mkdir blas lapack
cd interfaces/lapack ; mkdir C F77
cd interfaces/lapack/C ; mkdir src testing
cd interfaces/lapack/F77 ; mkdir src testing
cd interfaces/blas ; mkdir C F77
cd interfaces/blas/C ; mkdir src testing
cd interfaces/blas/F77 ; mkdir src testing
cd interfaces/lapack ; mkdir C2F
cd interfaces/lapack/C2F ; mkdir src
mkdir ARCHS
make -f Make.top startup
make[1]: Entering directory `/usr/local/atlas'
Make.top:1: Make.inc: No such file or directory
Make.top:325: warning: overriding commands for target `/AtlasTest'
Make.top:76: warning: ignoring old commands for target `/AtlasTest'
make[1]: *** No rule to make target `Make.inc'.  Stop.
make[1]: Leaving directory `/usr/local/atlas'
make: *** [startup] Error 2
mv: cannot stat ‘lib/Makefile’: No such file or directory
/home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: 450: /home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: cannot create lib/Makefile: Directory nonexistent
/home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: 451: /home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: cannot create lib/Makefile: Directory nonexistent
/home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: 452: /home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: cannot create lib/Makefile: Directory nonexistent
/home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: 453: /home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: cannot create lib/Makefile: Directory nonexistent
/home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: 509: /home/airfoil/Desktop/ATLAS_Install/ATLAS/./configure: cannot create lib/Makefile: Directory nonexistent
DONE configure

**Comment by JacobCrabill** [comment]
When it says "Permission Denied" that means you need sudo access to the system.  You can't install things to protected directories like /usr/local/ without admin access.
