### ISSUE TITLE
Fatal error 'Unable to open cubature file' at ../src/cubature_quad.cpp:75

### ISSUE THREAD

**Issue by popstar0426** [HiFiLES/HiFiLES-solver#108]
Hi:

   Sometime I meet this error below:
   Setting up mesh connectivity
  Fatal error 'Unable to open cubature file' at ../src/cubature_quad.cpp:75
  Fatal error 'Unable to open cubature file' at ../src/cubature_quad.cpp:75
  Done setting up mesh connectivity
  The solution is to source .bashrc again.
  Do you know this or do you have a improvement?

Best regards!
Yue

**Comment by mlopez14** [comment]
You need to create an environment variable HIFILES_HOME that contains the
path to the HiFiLES installation folder. The Tutorial on running the code
describes this in more detail.

**Comment by popstar0426** [comment]
Hi:
   I have done that with below text in my .bashrc.
  export HIFILES_HOME=/export/home/wangy/HiFiLES-solver
  export HIFILES_RUN=/export/home/wangy/HiFiLES-solver/bin
  export PATH=/export/home/wangy/HiFiLES-solver/bin:$PATH

   But I meet the error every time when I enter a cluter node.
   I need to source .bashrc, then the error disappears.
   It is not a big problem. I can use HiFiLES.

Best regards!

**Comment by mlopez14** [comment]
We'll try to get rid of this requirement... it is cumbersome.
