### ISSUE TITLE
What is relation of L_free_stream and length in mesh?

### ISSUE THREAD

**Issue by popstar0426** [HiFiLES/HiFiLES-solver#109]
Hi:
    I understand that L_free_stream is Reference length corresponding to the chosen Re.
    The example is very clear: chord length of airfoil.
    However I have a question with the mesh generation?
    For example: I generate a mesh around an airfoil with chold length =1. Then I should set the L_free_stream to 1. Yes, no problem.
    But if I generate an airfoil with chold length =0.2, which value should I set for the L_free_stream?
    
   

Best regards!
Yue

**Comment by mlopez14** [comment]
The discussion on non-dimensionalizaton in the documents addresses this
question directly. Please let us know if it is not clear.

**Comment by popstar0426** [comment]
Sorry, which document?

Best regards!

**Comment by mlopez14** [comment]
This one:

https://github.com/HiFiLES/HiFiLES-solver/wiki/Non-dimensionalization
