### ISSUE TITLE
Some questions with boundary layer simulation

### ISSUE THREAD

**Issue by popstar0426** [HiFiLES/HiFiLES-solver#110]
Hi:

   Suppose you do a boundary simulation, the inflow Reynolds number Re= 450 based on the inflow displacement thickness δ. The computational domain is x * y *z = 3000δ * 100δ * 120δ.  
   You made a  mesh box with 3000 * 100 * 120.
   Question: what is the value of  L_free_stream ?

Best regards!
Yue

**Comment by mlopez14** [comment]
It will depend on the actual mesh dimensions. These dimensions will be non-dimensional. Check out the examples here: https://github.com/HiFiLES/HiFiLES-solver/wiki/Non-dimensionalization

Let us know if you still have questions.
