### ISSUE TITLE
Fatal error 'environment variable HIFILES_HOME is undefined' at ../src/cubature_1d.cpp:74

### ISSUE THREAD

**Issue by maruthinh** [HiFiLES/HiFiLES-solver#111]
I get this Fatal error 'environment variable HIFILES_HOME is undefined' at ../src/cubature_1d.cpp:74
error while trying to run inviscid flow past a cylinder. how to fix this.? Please can somebody explain in brief, how to run different cases.?

**Comment by pytesnim** [comment]
hello,
how did you fix it? thanks
