### ISSUE TITLE
Implicit Time Stepping

### ISSUE THREAD

**Issue by popstar0426** [HiFiLES/HiFiLES-solver#112]
Hi:
   Do you have a plan to add Implicit Time Stepping to HiFiLES?

Best regards!

**Comment by mlopez14** [comment]
Yes, but that is still ongoing.

**Comment by popstar0426** [comment]
What can I do in the development?

**Comment by popstar0426** [comment]
Hi:

  Is there anything I can do in the development?

Best regards!
Yue
