### ISSUE TITLE
running code in parallel

### ISSUE THREAD

**Issue by sumit-sp** [HiFiLES/HiFiLES-solver#129]
Hey,
I am facing problem with configure_run.sh file.
Is it necessary to install ATLAS for parallel computing? Is there other way to do it.(like different software)
Also I am using CENTOS , so I guess the tutorial given for ubuntu is not working.
I am facing problems finding header files like BLAS_LIB etc

**Comment by JacobCrabill** [comment]
ATLAS is just one distribution of the BLAS library, so if you want BLAS support (to avoid significant slowdown), you'll need to supply the configure script with the location of cblas.h, libcblas.so, etc.

For running in parallel, you need a distribution of MPI, i.e. MPICH2, OpenMPI, etc., which should include the compiler-wrapper mpicxx.

If the configure script, or the compiler, cannot find some files, try looking for the file yourself, i.e.

locate cblas.h

and then supplying the directory it resides in (if any) to the configure_run.sh script.

Hope that helps!

**Comment by sumit-sp** [comment]
I have installed openmpi and provided location of mpi.h  . But while running code the mpirun command is not found.

**Comment by JacobCrabill** [comment]
You probably have to add the OpenMPI bin directory to your PATH variable (in your .bashrc or .cshrc, etc).

**Comment by sumit-sp** [comment]
Solved,
Actually I was not loading the module.
Thanks for help
