### ISSUE TITLE
Fatal error " Unable to open cubature file  at ../src/cubature_1d.cpp"

### ISSUE THREAD

**Issue by pytesnim** [HiFiLES/HiFiLES-solver#144]
Hi,
 I am trying to run testcase cylinder and I get following error message " Unable to open cubature file  at ../src/cubature_1d.cpp"
 I looked at a similar issue but did not solve my problem. 
I set the environment variables by writing them in ~bashrc as

export HIFILES_HOME=nurdan/Desktop/HiFiLES-solver-master/HiFiLES-solver-master/bin/HiFiLES
export HIFILES_RUN="nurdan/Desktop/HiFiLES-solver-master/HiFiLES-solver-master/bin/HiFiLES
export PATH=/export/home/nurdan/Desktop/HiFiLES-solver-master/HiFiLES-solver-master/bin:$PATH

and in src/cubature_1d.cpp file I wrote

filename="/home/nurdan/Desktop/HiFiLES-solver-master/HiFiLES-solver-master/data/cubature_1d.dat";
filename+= "/data/cubature_1d.dat";
What am I doing wrong?

Thanks for your help.

**Comment by JacobCrabill** [comment]
The HIFILES_HOME directory is the top-level directory of HiFiLES, not the path to the executable; so set your variables as:
export HIFILES_HOME=nurdan/Desktop/HiFiLES-solver-master/HiFiLES-solver-master/
export HIFILES_RUN="nurdan/Desktop/HiFiLES-solver-master/HiFiLES-solver-master/bin/
