### ISSUE TITLE
Minimum library versions

### ISSUE THREAD

**Issue by mahmoodn** [HiFiLES/HiFiLES-solver#145]
Hi,
What are the minimum/recommended libraries for HiDiLES? I mean the CUDA, gcc and BLAS versions.

**Comment by JacobCrabill** [comment]
Any version of BLAS should work; there are different different distributions but all should have the same API.  OpenBLAS is a popular distribution; ATLAS is also nice if you take the time to tune it for your specific system.
For gcc, I'm not sure what absolute minimum version will compile the code, but >= 4.8 will work fine.
For CUDA, the code was originally written around Fermi hardware, so the minimum SM architecture is 20 (but that hardware is practically obsolete now, so whatever CUDA version you have should be fine as long as it's compatible with your hardware).

Hope that helps!
