### ISSUE TITLE
HiFiLES Installation Problem

### ISSUE THREAD

**Issue by BenjaminDai** [HiFiLES/HiFiLES-solver#150]
Does anyone have ever successfully installed HiFiLES, if you did, Please do give me some advice or tutorial.
I've tried so many times installing HiFiLES, with or without mpi, it failed anyway. kind of frustrating.
My PC system is Ubuntu 18.04. I've installed OpenFOAM, SU2, etc successfully one or two month ago. And I've install autoconf with linux shell command "sudo apt-get install autoconf", ATLAS with "sudo apt-get install libatlas-base-dev". I have already installed openmpi library long time ago. 
When I tried to compile HiFiLES with BLAS and MPI, i edit file configure_run.sh, changed the location of header file and library file of ATLAS and openmpi.   Then i typed "bash configure_run.sh" in a terminal, it went almost well. But when i typed "make", i encountered various errors, such as "no rule to make parmetis...".
So i switched to compilation without BLAS and MPI, i changed to root user with "su root" command, and typed "./configure" and "make" in the terminal, and i got an error message with "make". Can anyone kindly give me some advice on this error message, or give me a tutorial on installation of HiFiLES. Thanks in advance. 
root@dwh-virtual-machine:/home/dwh/software/HiFiLES-solver-master# ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
<<< Configuring library with Metis support >>>
checking for thread local storage (TLS) class... __thread
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking dependency style of gcc... (cached) gcc3
checking whether gcc and cc understand -c and -o together... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
configure: creating ./config.status
config.status: creating Makefile
config.status: creating lib/Makefile
config.status: creating obj/Makefile
config.status: executing depfiles commands
config.status: executing libtool commands

Build Configuration Summary:

    Source code location: /home/dwh/software/HiFiLES-solver-master
    Install location: 	  /usr/local
    Version:              0.1
    Code Type:            DEBUG
    Compiler:             g++
    Preprocessor flags:    -D_NO_BLAS -DNO_PARMETIS -D_CPU 
    Compiler flags:       -g -O2 
    Linker flags:           
    Libraries:              
    BLAS support:         NO
    MPI support:          NO
    CUDA support:         NO 
    TecIO support:        NO

Additionally, don't forget to set the environment variable HIFILES_HOME
root@dwh-virtual-machine:/home/dwh/software/HiFiLES-solver-master# make
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /home/dwh/software/HiFiLES-solver-master/missing --run aclocal-1.11  -I m4
/home/dwh/software/HiFiLES-solver-master/missing: 行 52: aclocal-1.11: command not found
WARNING: `aclocal-1.11' is missing on your system.  You should only need it if
         you modified `acinclude.m4' or `configure.ac'.  You might want
         to install the `Automake' and `Perl' packages.  Grab them from
         any GNU archive site.
 cd . && /bin/bash /home/dwh/software/HiFiLES-solver-master/missing --run automake-1.11 --foreign
/home/dwh/software/HiFiLES-solver-master/missing: 行 52: automake-1.11: command not found
WARNING: `automake-1.11' is missing on your system.  You should only need it if
         you modified `Makefile.am', `acinclude.m4' or `configure.ac'.
         You might want to install the `Automake' and `Perl' packages.
         Grab them from any GNU archive site.
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /home/dwh/software/HiFiLES-solver-master/missing --run autoconf
configure.ac:30: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:122: error: possibly undefined macro: AM_CONDITIONAL
configure.ac:413: error: possibly undefined macro: AM_PROG_CC_C_O
configure.ac:414: error: possibly undefined macro: AM_PROG_LIBTOOL
Makefile:338: recipe for target 'configure' failed
make: *** [configure] Error 1

**Comment by JacobCrabill** [comment]
I'm guessing the issue may be related to the very old version of Automake this was written for.  Make sure you have automake, autoconf, libtool, etc. all installed, then give autoreconf a try.  Also make sure you have a METIS library installed.

HiFiLES hasn't been developed in many years now; I would suggest you try a more fully-featured solver like https://github.com/PyFR/PyFR.  We also have a somewhat more recent and similar code, ZEFR, that @romerojosh could possibly make available to you for research purposes if desired.

**Comment by BenjaminDai** [comment]
Jacob,
Thanks for your answer. By the way, have LES code been implemented in PyFR or ZEFR?

**Comment by JacobCrabill** [comment]
Not that I am aware of; the typical approach used with codes like these is to perform "implicit" LES, where the "implicit" comes from assuming that the amount of numerical dissipation introduced by your grid is on the order of the dissipation added by an explicit LES filter you might use.
