### ISSUE TITLE
How to execute the HiFILES?

### ISSUE THREAD

**Issue by sq3101** [HiFiLES/HiFiLES-solver#152]
Hi, 

I am new to this code. It has already been installed successfully. Just wondering how to execute this code in bash with MPI/GPU, can any developer or experienced user show me what command I should use to run a simulation in bash?

Many thanks for assistance.

**Comment by mlopez14** [comment]
Hi,

Have you tried the instructions here? https://github.com/HiFiLES/HiFiLES-solver/wiki/Execution

**Comment by sq3101** [comment]
> Hi,
> 
> Have you tried the instructions here? https://github.com/HiFiLES/HiFiLES-solver/wiki/Execution

Thanks a lot, I'll figure out how to use it.
