### ISSUE TITLE
How to set boundary conditions?

### ISSUE THREAD

**Issue by popstar0426** [HiFiLES/HiFiLES-solver#28]
Hi:
 
   I tried to made a mesh for HiFiLES by Gambit. 
   Do I need to set boundary conditions in Gambit?
   However, when I chose generic solver in Gambit (the solver can export .neu mesh), there is no types for the boundary settings, like wall, inlet or other boundary types for HiFiLES. 
   What kind of software should I use for the pre-processing of HiFiLES?
   
Best regards!
Yue Wang

**Comment by yilvqingyan** [comment]
Hi
Could you help me?
Could you send me an neu.file and the input file for the case (2D) NACA 0012 0° AoA?
my email is 2508723155@qq.com

Best regards!
chen
