### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by jgrisham4** [HiFiLES/HiFiLES-solver#34]
I've been trying to compile HiFiLES for a couple of hours now, but I keep running into an interesting problem.  I was originally trying to compile with MPI, ParMETIS, and TecIO on a Linux cluster (running CentOS), but wasn't successful.  I tried the most simple installation possible, no options besides --prefix, but the problem persists.  So, I tried to compile on my local machine (Fedora 20).  I encountered the exact same problem.  Running ./configure seems fine, but when I run make, I get the following:

```
make
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /home/james/codes/HiFiLES-solver/missing --run aclocal-1.11  -I m4
/home/james/codes/HiFiLES-solver/missing: line 52: aclocal-1.11: command not found
WARNING: `aclocal-1.11' is missing on your system.  You should only need it if
         you modified `acinclude.m4' or `configure.ac'.  You might want
         to install the `Automake' and `Perl' packages.  Grab them from
         any GNU archive site.
 cd . && /bin/sh /home/james/codes/HiFiLES-solver/missing --run automake-1.11 --foreign
/home/james/codes/HiFiLES-solver/missing: line 52: automake-1.11: command not found
WARNING: `automake-1.11' is missing on your system.  You should only need it if
         you modified `Makefile.am', `acinclude.m4' or `configure.ac'.
         You might want to install the `Automake' and `Perl' packages.
         Grab them from any GNU archive site.
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /home/james/codes/HiFiLES-solver/missing --run autoconf
configure.ac:30: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:122: error: possibly undefined macro: AM_CONDITIONAL
configure.ac:413: error: possibly undefined macro: AM_PROG_CC_C_O
configure.ac:414: error: possibly undefined macro: AM_PROG_LIBTOOL
make: *** [configure] Error 1
[james@feynman HiFiLES-solver]$ 
```

The first thing I see is this:
```You might want to install the `Automake' and `Perl' packages.```
Automake and Perl are both up-to-date.  I also see a warning that aclocal is missing, which also seems to be wrong:
```
[james@feynman HiFiLES-solver]$ aclocal --version
aclocal (GNU automake) 1.13.4
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
```
I see a lot of notes about "You should only need this if you modified ...", but I didn't touch any of the files.

Any ideas what I'm doing wrong here?

Thanks,

James

**Comment by jrbull** [comment]
James,

Thank you for sharing your fix with us. How did you come up with it?
Regards,
Jonathan

Postdoctoral Scholar
Dept of Aero/Astro Engineering
Stanford University

**Comment by jgrisham4** [comment]
?Jonathon,


If I remember correctly, I tracked down all the "undefined" macros in the output and added those.  It has been a while so I don't remember all the details.


Thanks,


James

________________________________
