### ISSUE TITLE
Channel flow test case

### ISSUE THREAD

**Issue by YakAllonsy** [HiFiLES/HiFiLES-solver#35]
Hi,

I'm trying to run a channel flow test case using HiFiLES. It seems that HiFi has a built-in channel flow. I have several issues about that. First, I think there might be a typo in the perturbation equation (the position of the '-' sign, line 596, eles.cpp). And could you provide me with some references of the theoretical basis of this perturbation form? I believe it's adding perturbation by using the wall normal injection, but I've never seen this before. Second, I always got a NaN body force. Do you have any suggestions on that?

Thank you.

Yongkai

**Comment by jrbull** [comment]
Body force fix merged, perturbation bug fixed.
