### ISSUE TITLE
nondimensionalization

### ISSUE THREAD

**Issue by jiamin0329** [HiFiLES/HiFiLES-solver#37]
Hi,
   it can be found that a non-dimensional NS equation is solved in the solver. there should be a term  (1/Re) or (Ma/Re) in the viscous term, for the equation is non-dimensionalized by free stream velocity here, there should be 1/Re in the viscous term, but i can not found it in viscFlux function. where can i find the 1/Re in the viscous term?

Best Regards,
Jiamin

**Comment by mlopez14** [comment]
Hi Jiamin,

You can find the non-dimensionalization steps very close to the end of the method input::setup. This would be in file input.cpp.

The non-dimensionalization is done in a fairly round-about way, as many of the reference quantities are used in other parts of the code. Nevertheless, the non-dimensionalization of the kinematic viscosity, mu, does bring up the term (1/Re).
