### ISSUE TITLE
channel flow

### ISSUE THREAD

**Issue by YakAllonsy** [HiFiLES/HiFiLES-solver#39]
Hi,
I'm just wondering are there any limitations to run the channel flow? I try to run this case with different parameters, which always gave me NaN residual. And for the updated version of the code, it seems that the body force term is designed for the periodic hill. Is that also valid for the channel flow case?

Thank you.

**Comment by jrbull** [comment]
What parameters did you try to change? Can you send your input file and mesh for me to run?

You can change between the channel and periodic hill cases by commenting out/uncommenting the lines in eles::evaluate_body_force. However, the initial perturbation used to start turbulent decay (defined in eles::set_ics) is hard-coded to the channel. It can be quite easily modified to work for the periodic hill, just change the lengthscale parameters and set the perturbation to be zero below the height of the hill.

Thanks,
Jonathan

Postdoctoral Scholar
Dept of Aero/Astro Engineering
Stanford University

**Comment by YakAllonsy** [comment]
Hi,
Attached are the mesh and input files. I'm trying to run the channel case.
I'll make a double check to make sure I didn't make any mistakes.

Thank you very much



On Thu, Mar 5, 2015 at 3:37 PM, jrbull <notifications@github.com> wrote:

> What parameters did you try to change? Can you send your input file and
> mesh for me to run?
>
> You can change between the channel and periodic hill cases by commenting
> out/uncommenting the lines in eles::evaluate_body_force. However, the
> initial perturbation used to start turbulent decay (defined in
> eles::set_ics) is hard-coded to the channel. It can be quite easily
> modified to work for the periodic hill, just change the lengthscale
> parameters and set the perturbation to be zero below the height of the hill.
>
> Thanks,
> Jonathan
>
> Postdoctoral Scholar
> Dept of Aero/Astro Engineering
> Stanford University
>
> On Mar 5, 2015, at 12:01 PM, YakAllonsy <notifications@github.com> wrote:
>
> > Hi,
> > I'm just wondering are there any limitations to run the channel flow? I
> try to run this case with different parameters, which always gave me NaN
> residual. And for the updated version of the code, it seems that the body
> force term is designed for the periodic hill. Is that also valid for the
> channel flow case?
> >
> > Thank you.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HiFiLES/HiFiLES-solver/issues/39#issuecomment-77446520>
> .
>



-- 


CHEN, Yongkai
