### ISSUE TITLE
GMSH reader does not work for quads

### ISSUE THREAD

**Issue by JacobCrabill** [HiFiLES/HiFiLES-solver#4]
Discovered today that, although the Gmsh reader works properly for triangles, it does not appear to be functioning for quads (variable "xv" appears to be scrambled after reading mesh - proper number of nodes, but nodes out of order, and duplicates).  Will attempt to fix over the weekend.

For reference, here is a simple 3x3 cartesian mesh that HiFiLES fails to read:

$MeshFormat
2.2 0 8
$EndMeshFormat
$PhysicalNames
5
1 1 "Sup_Out"
1 2 "Sup_In"
1 3 "Sup_In"
1 4 "Sup_Out"
1 5 "FLUID"
$EndPhysicalNames
$Nodes
16
1 -10.000000 -10.000000 0.000000
2 -3.333333 -10.000000 0.000000
3 3.333333 -10.000000 0.000000
4 10.000000 -10.000000 0.000000
5 -10.000000 -3.333333 0.000000
6 -3.333333 -3.333333 0.000000
7 3.333333 -3.333333 0.000000
8 10.000000 -3.333333 0.000000
9 -10.000000 3.333333 0.000000
10 -3.333333 3.333333 0.000000
11 3.333333 3.333333 0.000000
12 10.000000 3.333333 0.000000
13 -10.000000 10.000000 0.000000
14 -3.333333 10.000000 0.000000
15 3.333333 10.000000 0.000000
16 10.000000 10.000000 0.000000
$EndNodes
$Elements
21
1 3 2 5 5 1 2 6 5
2 3 2 5 5 2 3 7 6
3 3 2 5 5 3 4 8 7
4 3 2 5 5 5 6 10 9
5 3 2 5 5 6 7 11 10
6 3 2 5 5 7 8 12 11
7 3 2 5 5 9 10 14 13
8 3 2 5 5 10 11 15 14
9 3 2 5 5 11 12 16 15
10 1 2 1 1 13 14
11 1 2 1 1 14 15
12 1 2 1 1 15 16
13 1 2 2 2 1 2
14 1 2 2 2 2 3
15 1 2 2 2 3 4
16 1 2 3 3 1 5
17 1 2 3 3 5 9
18 1 2 3 3 9 13
19 1 2 4 4 4 8
20 1 2 4 4 8 12
21 1 2 4 4 12 16
$EndElements

**Comment by jmaximelv** [comment]
+1
Dose it work now?

**Comment by JacobCrabill** [comment]
Yes, it works now.

**Comment by jmaximelv** [comment]
Thats great! I'll have a try.

Bests
Maxime
