### ISSUE TITLE
What is the maximum of mesh cells?

### ISSUE THREAD

**Issue by sherry413** [HiFiLES/HiFiLES-solver#40]
Hi,

I am wondering what is the largest mesh file you have used up to now? I am running a case with 1GB gambit mesh file and it runs out the memory of 16 processors. Thank you.

Sherry

**Comment by mlopez14** [comment]
This is a problem we're looking into. Would you mind sharing the number of elements of each type and the degree of the polynomial you are using for the discretization? Is this when running in CPU or GPU mode?

The number of degrees of freedom (DoFs) in 3-D Navier-Stokes is of order N*(p+1)^3, where N is the number of elements and p is the order of the polynomial in each element. Each of these DoFs has 12 fields for solution and flux, plus a determinant of jacobian value. In addition, each element needs to keep track of its connectivity, node values, and values of solution and flux at the interfaces. We need to store all of this 2 times, as we use the RK45 method (described in "Fourth-order 2N-storage Runge-Kutta schemes", by Carpenter and Kennedy).

As each value is a double, it occupies 8 bytes. As an approximation, the storage requirement should be about 208*N*(p+1)^3 bytes.

@ramezaniua reported a bug in which the CPU implementation adds major memory overhead in small problems (7MB in one CPU become 10MB per CPU in a multi-CPU run). Are you seeing something similar?

**Comment by sherry413** [comment]
I used a mesh for about 2 million elements with polynomial order equal to zero, which requires  124100572kb for 32 processors when reading the mesh information. I found that it requires approximately 2GB for adding one more processor. I think the additional memory for allocating in the parallel block of the code is acceptable but I have no idea the mesh part requires that much memory. Thank you.

**Comment by arctanx** [comment]
So according to @mlopez14 , the TGV-32 case with 31^3 elements should require 320*31^3*(3+1)^3 bytes, that's approximately 582 M. However, it actually took 7G of memory in serial. I'm wondering why it requires so much memory?

**Comment by mlopez14** [comment]
@arctanx you bring a good point. Each element requires quite a bit of more memory. The calculations I mentioned before are an order of magnitude estimate. Memory requirements can be estimated as C N p^3 where N is the number of elements, p is the polynomial order, and C is a coefficient dependent on the type of simulation, the type of elements, and the number of dimensions. The coefficient turns out to be fairly large. We'll post the details in a few days.
