### ISSUE TITLE
input file for [(3D) SD7003 wing section, 4° AoA, Re = 10,000] case? 

### ISSUE THREAD

**Issue by popstar0426** [HiFiLES/HiFiLES-solver#41]
Hi:

   Could you share the input file  for [(3D) SD7003 wing section, 4° AoA, Re = 10,000] case? 
   The wiki is not updated for quite a long time.

Best regards!
Yue Wang

**Comment by mlopez14** [comment]
Indeed; it's my fault. I haven't tracked down that input file. 

In the meantime, what problems are you having using your own input file?

**Comment by popstar0426** [comment]
Hi:

  I run a 2D naca0012 case. The time step was so small with 5*10^(-7).
  If I increase it, the "nan residual" will come out.
  The thing is that the mesh is really  coarse. 
  So I wonder to study a suceeded case of airfoil?
  If you have one, could you send me with the input file and .geo (Gmsh)?
  My email: 282186964@qq.com

Best regards!
Yue
