### ISSUE TITLE
Cylinder Case Error

### ISSUE THREAD

**Issue by BijanZarif** [HiFiLES/HiFiLES-solver#42]
Hi,

I have installed HiFiLES code according to the instruction in the page "https://github.com/HiFiLES/HiFiLES-solver/wiki/Installation" without any problem (including running 'configure' and 'make' commands).
And the compiled executable was created in "./bin/HiFiLES" folder.
After that I was intended to run the cylinder example and used this command in the terminal:
'HiFiLES input_cylinder_visc'
But I faced the following error.

---------------------- Non-dimensionalization ---------------------
uvw_ref: 69.4256
rho_free_stream: 5.38898e-06
rho_c_ic=1
u_c_ic=1
v_c_ic=0
w_c_ic=0
mu_c_ic=0.05

----------------------- Mesh Preprocessing ------------------------
reading connectivity ... 
done reading connectivity
reading vertices
vrtlist: 714, 27, 4, 40
done reading vertices
Setting up mesh connectivity
Done setting up mesh connectivity
reading boundary conditions
Gambit mesh specs from header: , 1468, 714, 1, 3, 2
GROUP:          1 ELEMENTS:        714 MATERIAL:          2 NFLAGS:          1
                         fluid.1
done reading boundary conditions

---------------- Flux Reconstruction Preprocessing ----------------
initializing elements
tris
Initializing tris
Fatal error 'environment variable HIFILES_HOME is undefined' at ../src/cubature_1d.cpp:74

Would you mind helping me to fix this problem?
Thank you.

Bijan

**Comment by jrbull** [comment]
Bijan,
Please add the following to your .bashrc file or equivalent:

export HIFILES_HOME=<path_to_HiFiLES_directory>
export HIFILES_RUN=<path_to_HiFiLES_directory>/bin

This instruction should have been included in the wiki so thanks for bringing this to our attention.
Cheers,
Jonathan
Postdoctoral Scholar
Dept of Aero/Astro Engineering
Stanford University

**Comment by BijanZarif** [comment]
Jonathan
It worked.

Thanks a lot.
Bijan
