### ISSUE TITLE
Fatal error 'NaN residual encountered. Exiting' at ../src/output.cpp:1417

### ISSUE THREAD

**Issue by popstar0426** [HiFiLES/HiFiLES-solver#43]
Hi:

   When I run a 3D case of naca0012, I met a fata error : Fatal error 'NaN residual encountered. Exiting' at ../src/output.cpp:1417.
   There is somgthing wrong with "norm_type not recognized".
   I made the mesh by myself. It seems somt thing wrong when I extruded the 2D mesh.
   I am using gmsh. The 2D case was OK to run except the smaller time step.
 

Best regards!
Yue

**Comment by mlopez14** [comment]
A NaN can be caused by too large of a time-step, too large of a Reynolds number, or too coarse of a grid.

When is the "norm_type not recognized" error appearing?

**Comment by popstar0426** [comment]
Hi:

   I succeeded in running a 2D case (naca0012 airfoil) with the mesh. The time step was 0.0000005. Everything looked OK.
  Then I extruded the 2D mesh to a 3D mesh.  The error appeared. 
  Could you share me a 3D naca0012 mesh?
  Or could you have a look with my 3D mesh?
  I used a gmsh.

Best regards!
