### ISSUE TITLE
Is the any sequence to read the code?

### ISSUE THREAD

**Issue by popstar0426** [HiFiLES/HiFiLES-solver#44]
Hi:
   
    There are many files with *.cpp.
    If I want to read the code, what should I do?
    
Best regards!
Yue

**Comment by mlopez14** [comment]
The best place to start would be the file "HiFiLES.cpp" file, where the main() function is.

The file "eles.cpp" contains the most important functions used for calculating the residual, and "array.cpp" has all the methods of the core data structure (an array class).

We suggest using Qt Creator to navigate the code easily: https://github.com/HiFiLES/HiFiLES-solver/wiki/Building-and-Running-with-Qt-Creator
