### ISSUE TITLE
parallel installation and run my own case

### ISSUE THREAD

**Issue by paipaizhu** [HiFiLES/HiFiLES-solver#45]
hi:
when I run ./configure_run.sh.there is problem here:err ParMETIS requested but library file not found.I do not kown how to fix it .is it need install the necessary libraries?
if i want to run my own case ,can you tell me the process?

Best regards!
Shibin Zhu

**Comment by yilvqingyan** [comment]
Hi
I can help you.I have learnt how to run one case,my email is 2508723155@qq.com
Please email me.

Best regards!
chen

**Comment by mlopez14** [comment]
What options in the configure_run.sh file are you using? The default ones would build and link ParMETIS for you: 
# Basic User-Modifiable Build Settings [Change these as desired]
NODE="CPU"              # CPU or GPU
CODE="RELEASE"            # DEBUG or RELEASE
BLAS="ATLAS"               # ATLAS, STANDARD, ACCLERATE, or NO
PARALLEL="YES"           # YES or NO
TECIO="NO"              # YES or NO
METIS="YES"              # Build & link to the HiFiLES-supplied ParMETIS libraries? YES or NO
