### ISSUE TITLE
Could you share any 3D case with gmsh mesh? 

### ISSUE THREAD

**Issue by popstar0426** [HiFiLES/HiFiLES-solver#46]
Hi:

   Could you share any 3D simulation with gmsh mesh?
   Could you please share the .geo file and the input file?
   If it is a LES simulation, it would be better.

Best regards!
Yue

**Comment by popstar0426** [comment]
Or anyone can help me?
Please send me by email: 282186964@qq.com

Thank you very much!

**Comment by mlopez14** [comment]
At the moment we do not have gmsh meshes, although they are supported by the solver. What errors are you encountering with the meshes you create?
