### ISSUE TITLE
Could you help me?

### ISSUE THREAD

**Issue by yilvqingyan** [HiFiLES/HiFiLES-solver#47]
Hi
I have made a neu for HiFiLES by Gambit.
but I failed  to set the boundary conditions after many times trial
Could you send me an neu.file and the input file for the case (2D) NACA 0012 0° AoA?  
my email is 2508723155@qq.com
Thank you very much!

Best regards!
chen

**Comment by mlopez14** [comment]
The boundary conditions should look just like the boundary conditions in the cylinder testcase. Open the .neu file [here](https://github.com/HiFiLES/HiFiLES-solver/blob/master/testcases/navier-stokes/cylinder/cylinder_2ndorder_tri_vis.neu) and notice that after [line 2273](https://github.com/HiFiLES/HiFiLES-solver/blob/master/testcases/navier-stokes/cylinder/cylinder_2ndorder_tri_vis.neu#L2273), the Sup_in and Isotherm_Fix boundary conditions appear. 

After creating the mesh in Gambit, you can choose to name the boundaries.

A good tutorial on how to create meshes with Gambit can be found [here](http://grid-generation.blogspot.in/2011/05/gambit-viscous-grid-for-naca0016-airfoil.html). 

In the tutorial, in step 7, replace "PRESSURE_FAR_FIELD" with "Sup_in" and "WALL" with "Isotherm_Fix" to apply the boundary conditions related to HiFiLES.

**Comment by yilvqingyan** [comment]
Hi
Thank you for your help.I solved this problem.
Thank you very much.
Best regards!
chen
