### ISSUE TITLE
help for "Subsonic inflow characteristic" boundary cond

### ISSUE THREAD

**Issue by jmaximelv** [HiFiLES/HiFiLES-solver#48]
Hi,
I've run a case (2D, Ma~0.1) in which the inflow boundary condition is "Subsonic inflow characteristic".  And I got the u-velocity champ with value 0.4 !=1 (0.4 is just an example, what count is it < 1 ) far away from key zone of simulation (i.e., the zone where all variables vary smoothly). I think it could be the inflow boundary condition for my problem.
I've checked in the SU2 code (file solver_direct_tne2.cpp, line 4178), but I don't get any further information. Can, anyone, give me some references for this boundary condition?
Thanks in advance!
maxime LV

**Comment by jewatkins** [comment]
Hi maxime LV,

Are you simulating an internal or external flow? If you're simulating an external flow, try using the "Char" boundary condition. This should work as a nearfield or farfield boundary condition. The "Subsonic inflow characteristic" boundary condition can be used for internal flows. See "Numerical Computation of Internal and External Flows: The Fundamentals of Computational Fluid Dynamics" by Charles Hirsch for more detail.

-Jerry

**Comment by jmaximelv** [comment]
Hi Jerry,
Thanks. I'm simulating an external flow. I'll change the corresponding boundary to "Char", and to compare the results.
Maxime

**Comment by yilvqingyan** [comment]
Hi jerry
could you help me?I have a question that I can not understand.in the cylinder testcase,The boundary conditions are "Sup_In "and"Sup_In ",why not "Sup_In "and"Sup_Out"?
And what is the differerence between"Sub_In_Simp"and"Sub_In_Char".
Best regards!
chen

**Comment by jmaximelv** [comment]
Hi Jerry,
What your suggest do works. Thanks!
Maxime

**Comment by jewatkins** [comment]
Great! I'm glad it worked. Let me know if you have anymore questions.

-Jerry
