### ISSUE TITLE
A "strange" phenomenon troubled me 

### ISSUE THREAD

**Issue by jmaximelv** [HiFiLES/HiFiLES-solver#49]
Hi all,
I recently use HiFiLES (DNS) to simulate a 2D external flow. It stop at a certain time step for NaN error called by "calc_diagnostic_fields_ppts" (eles.cpp, in fact, it's "u" who should be attributed to).  I then halve the timestep  about 5 times, but they are all stop at the same ITERATION step! Both euler and RK advance methods have been tried. 
It just conflict with my understanding. Can anyone help me out?
Thanks in advance!
Maxime

**Comment by jrbull** [comment]
Maxime,
Currently the only place where the code checks for NaNs is in the diagnostics routines, so if the main solver is diverging that is where it would be detected. However, that it stops after identical numbers of timesteps is indeed curious. Can you send me your input file and mesh? Are you using the most recent version of the code?
Cheers,
Jonathan
Postdoctoral Scholar
Dept of Aero/Astro Engineering
Stanford University

**Comment by jmaximelv** [comment]
Hi Jonathan,
I've sent you the files last Friday as you demanded. Have you found the same phenomenon? 

Best regards,
Maxime

**Comment by mlopez14** [comment]
Are you using forward Euler time-stepping? That would explain the unconditional instability.

If this is happening with RK4, something else is going on.

**Comment by jmaximelv** [comment]
Hi mlopez14,
I think I've used RK. 
order                             // Order of basis polynomials
1
adv_type                          // 0: Forward Euler, 3: RK45
3
LES                               // 0: no LES, 1: LES
0

Best regards,
Maxime

**Comment by mlopez14** [comment]
Would you mind supplying a bit more of information?

Please mention the time-steps you are using with RK45 and copy-paste the corresponding output values of the residuals before the code NaNs.

For example:

time-step = 0.0001
  Iter       Res[Rho]   Res[RhoVelx]   Res[RhoVely]      Res[RhoE]       Fx_Total       Fy_Total
100   0.25207658     1.16561679     0.42397671     13.03689598    22.76129223    0.00754981     
Execution time= 3.748111 s

time-step = 0.0002
  Iter       Res[Rho]   Res[RhoVelx]   Res[RhoVely]      Res[RhoE]       Fx_Total       Fy_Total
100   0.11527078     0.51222414     0.44148805     6.70895905     20.84942289    0.11639832     
Execution time= 3.744929 s

**Comment by jrbull** [comment]
Maxime,
I haven’t received any files from you. Did you send them to my Stanford address?
Cheers,
Jonathan
Postdoctoral Scholar
Dept of Aero/Astro Engineering
Stanford University

**Comment by jmaximelv** [comment]
Hi mlopez14,
Sorry for a mistake in the last response. I use initially Euler for some different dt. And at last I try RK. But the results are the same.
time-step=0.00001
  Iter       Res[Rho]   Res[RhoVelx]   Res[RhoVely]      Res[RhoE]       Fx_Total       Fy_Total
265800     0.01792417     0.04790000     0.09015685     0.20764518     0.05963852     0.08538920
265805     0.01874922     0.04914375     0.09487151     0.21653885     0.05948749     0.08533728
Fatal error 'NaN in residual, exiting.' at ../src/eles.cpp:1703

Best regards,
Maxime

**Comment by mlopez14** [comment]
Can you show the output for a time-step of 1e-7 right before the code NaNs?

**Comment by jmaximelv** [comment]
Yes, but it may need some time as the last restart file is at 260000.
Best regards.
Maxime

**Comment by mlopez14** [comment]
Ok, thanks. Try then with a time-step of 2e-5 (twice what you mentioned before). And paste the output before the code NaNs.

**Comment by mlopez14** [comment]
Make sure to start from the beginning, not using a restart file.

**Comment by jmaximelv** [comment]
Hi Jonathan,
Sorry, I've sent to notifications@github.com. I just re-sent to your Stanford email.
Best regards,
Maxime

**Comment by jmaximelv** [comment]
Hi mlopez14 ,
Thanks. I'll try that at some time appropriate as I'm running another case.
Best regards,
Maxime

**Comment by mlopez14** [comment]
No problem. Take your time.

**Comment by jmaximelv** [comment]
Hi mlopez14，
Thanks! I think if I run the case from the start.  It should have different behaviors with different time steps. The question is if I run a case with Nan occur at an rather large time, I  then try to diminish the time step. It shouldn't stop at almost the same step?!
Best regards,
Maxime

**Comment by jmaximelv** [comment]
The question is if I run a case with Nan occur at an rather large time, I then try to diminish the time step and restart the simulation from some restart time. It shouldn't stop at almost the same step?!

**Comment by mlopez14** [comment]
Ah, ok, I'm glad it is not ending at the same iteration number even when the time step is changed and the simulation is started from the beginning.

Two things may be happening:
1. The initial time-step is larger than it should for a specific state of the flow. When you restart using a restart file and use a smaller time-step, the solution might already be on its way to growing out of bounds, so the smaller time-step will not avoid the NaN, just postpone it.

2. The case you are running may be asking too much of the mesh you have (I think this is what is happening in your case). It is possible you are trying to run a high Reynolds number in a coarse mesh. This will create aliasing problems (trying to capture high frequencies with a coarse mesh will introduce false low frequency energy into the solution), which will make your solution to grow unbounded no matter the time-step you use. I'm implementing some filters right now that should help with a situation like this one. For now, the only solution to this is to refine the grid or decrease the polynomial order. You should be able to restart with a polynomial order of 1 even if the restart file was created with a polynomial of a different order.

Can you try restarting with polynomial order 1 and report back on whether or not it is NaNing?

**Comment by jmaximelv** [comment]
Hi mlopez14，
Yes It is very probably that I'm running a high Reynolds (10^5) number case in a coarse mesh.  But the polynomial which I used is just of order 1.
Best regards,
Maxime

**Comment by jmaximelv** [comment]
Hi mlopez14，
I've also run the same case with SA and order=3. It get more easy to reach unbounded (Nan error) state.

**Comment by mlopez14** [comment]
That is correct. As the SA turbulence model introduces some very stiff terms, the time-step restriction is even more severe. We're working on implementing some form of implicit time-step so SA can be truly useful. 

On the other hand, keep in mind that the SA turbulence model was developed for the RANS equations assuming the flow --under specific turbulent conditions-- reaches a statistically steady state. With LES of vortex-dominated flows this assumption may no longer hold and thus the model's predictive qualities are not guaranteed.

**Comment by jmaximelv** [comment]
Hi mlopez14,
Thanks!!  But what dose "the model's predictive qualities are not guaranteed" mean? You mean on a coarse mesh, LES's predictive qualities are not guaranteed? Or something about SA model? Or ...? 
Best regards,
Maxime

**Comment by mlopez14** [comment]
I meant SA model's predictive qualities are not guaranteed when the assumptions used to develop it are not satisfied. With LES you are letting the PDE behave as it chooses (within the limitation of the grid and discretization choices) so the accuracy does not rely as much on the modeling approach. 

In the original paper the authors mention how they go about calibrating the SA turbulence model: http://arc.aiaa.org/doi/abs/10.2514/6.1992-439

**Comment by jmaximelv** [comment]
Thanks! 
Sincerely,
Maxime
