### ISSUE TITLE
Questions about Turbulence model

### ISSUE THREAD

**Issue by popstar0426** [HiFiLES/HiFiLES-solver#53]
Hi:
 
   The default value of turb_model = 0.
   What does “0” mean here, RANS model or LES model or no model at all?
   How to specify different turbulence model in HiFiLES?
   There is LES options in the wiki. Could you give more introduction on RANS and Hybird LES?
   If I would like to run DNS simulations?
   What should I do?

Best regards!
Yue

**Comment by jrbull** [comment]
Yue,

Thanks for your question.
The turb_model parameter defines whether a RANS model is used. Currently the Spalart Allmaras model is in the code. This solves an additional equation for the turbulent viscosity, nu_tilde. The turb_model name should perhaps be changed to rans_model.

LES models are not affected by this parameter; they are chosen separately by selecting LES=1 and an appropriate value of SGS_model. The WALE model is recommended for most cases at present. This model does not require any filter options except filter_ratio, which should be set to 2.

Hybrid RANS-LES is not supported yet.

Let us know if you have any more questions.
Cheers,

Postdoctoral Scholar
Dept of Aero/Astro Engineering
Stanford University

**Comment by popstar0426** [comment]
hi:

   So the turb_model=0 means the SA model is used. Am I right?
   If I want to run DNS simulations, should i change to LES model, without any SGS model (normally called Implicit LES)?

Best regards
Yue

**Comment by jrbull** [comment]
turb_model = 0 means no RANS model, turb_model = 1 means SA model.
For DNS, don’t use RANS or LES models: set LES=0 and turb_model=0.

Postdoctoral Scholar
Dept of Aero/Astro Engineering
Stanford University
