### ISSUE TITLE
Questions about Cyclic Boundary Conditions 

### ISSUE THREAD

**Issue by popstar0426** [HiFiLES/HiFiLES-solver#54]
Hi:
  
   I have some questions on Cyclic Boundary Condtions.
  Assume a case like   SD7003 wing section, 4° AoA, Re = 10,000.
   I would like to set "Char" for the farfield, "Adiabat_Fix" for the Wind section, and "Cyclic" for the two faces on the spanwise.
  Questions:
  What are the values of the below parameters in the input file?
  dx_cyclic: Length (in x-direction) of periodic domain  
  dy_cyclic: Length (in y-direction) of periodic domain
  dz_cyclic: Length (in z-direction) of periodic domain   

Best regards!
Yue

**Comment by mlopez14** [comment]
Good question! We should add this to the Wiki (perhaps you could help us out here?)

The dx values should correspond to the distance between the faces labeled cyclical. At the moment, the code does a brute-force search for the corresponding faces. So for example, suppose one face is at the y-z plane x_0 = -1 and the other face is at the y-z plane x_1 = 1, the value of dx_cyclic should be 2.

**Comment by popstar0426** [comment]
Hi:

   Consider a case like SD7003 wing section, 4° AoA, Re = 10,000.
   Two cyclical faces are set on the z direction with a distance of 0.2.
   So the dz_cyclic = 0.2, am I right?
   How about the other two directions, dx_cyclic and dy_cyclic?
   I put "Infinity" on both of them. However, the simulations could not run. 
   Then I leave no data for their values (delete the "Infinity")?
   The simulation could run for a while.
   It seems the default value for dx_cyclic and dy_cyclic are not "Infinity" (on the wiki).

Best regards！
Yue

**Comment by mlopez14** [comment]
Correct, as the mesh does not extend to infinity, there must be a finite quantity in dx_cyclic and dy_cyclic.

Perhaps the simulation was able to run because it found the cyclic boundaries. It performs a brute-force search to find the matching boundaries labeled "cyclic".

**Comment by popstar0426** [comment]
Hi:
  
  Is there any  Instant Messaging group for fans of HiFiLES?
  I would like to join in it.

Best regards!
Yue

**Comment by mlopez14** [comment]
Not yet. How do you think we could use something like that and what option do you propose?

**Comment by popstar0426** [comment]
Hi:

  How about QQ: http://www.imqq.com/  .
  I have build a group called "HiFiLES Fans" (group ID: 399819206) in QQ.
  There are 37 fans inside. Many of them are undergraduate students who are interested in CFD and HiFiLES. 
  In QQ, anyone (who is interested on anything) can search by name or group ID to find groups of people with the same interest. For example, there are several groups interested in OpenFoam. The biggest one have 1436 people inside. Everyone can ask questions and communicate with each other.

If you are interested in it, just download QQ and join in the group "HiFiLES Fans" by search name or group ID.
 If you have any questions about QQ, please ask Chinese Students around about it. Thay all know that and use it. 

Best regards!
Yue

**Comment by popstar0426** [comment]
Hi:

  Better things with QQ:
  1, You can ask questions as you want at any time, you can answer questions as you want at any time;
  2, Download and Upload files as you want; 
  3, You can show pictures at any time;
  4, Nobody will laugh at you when you are a beginner. Because everyone does not know you except your nick name in group.
  5, ......

Best regards!
Yue

**Comment by mlopez14** [comment]
It does sound interesting. The fact that one needs to sign up and download an app to read the messages might not make it a good platform for answering questions about the code. I'll join the group, but would re-direct any questions about HiFiLES to github for now.

We are looking into creating a forum at http://www.cfd-online.com/Forums/
