### ISSUE TITLE
Questions about nondimensionalization

### ISSUE THREAD

**Issue by jmaximelv** [HiFiLES/HiFiLES-solver#55]
Hi all,
I've questions about the dimensionless. In the code, I cannot find the dimensionless process for the physical coordinate (x,y,z) and the time (t). Is it true? 
If it's true, how to keep the consistency?  And the dt in the input file has dimension or not?

Best regards,
Maxime

**Comment by mlopez14** [comment]
There is this previous question on non-dimensionalization: https://github.com/HiFiLES/HiFiLES-solver/issues/37

What I would add to that is that t is non-dimensionalized with L_ref/|U_ref|.

**Comment by jmaximelv** [comment]
Thanks mlopez14.

Best regards
Maxime

**Comment by jmaximelv** [comment]
Hi mlopez14,
I want to make sure that the space coordinates are not dimensionless by the reference length L_ref? It's OK as most of the works are done in the standard elements and we only come back to the physical space when we want to know the common value at the interface. Because we multiply something like J (J^{-1}) when we transform from physical  space (standard element) to standard element (physical space).   Is that right?
But it just looks uncomfortable as the time and velocity are both dimensionless, but the space coordinates (from tecplot for example) are non dimensionless.

Best regards
Maxime

**Comment by mlopez14** [comment]
Maxime,

L_ref does play a role in non-dimensionalizing the conservation quantities: density, momentum, and energy, and time and spatial derivatives. It has no bearing on the calculations themselves, only in interpreting the physical quantities that are obtained from the simulation and the dimensions of the mesh in real life. L_ref is used to initialize the flow only.

Time is non-dimensionalized as follows:
$U_{ref} = Ma  \sqrt(\gamma R T)$
$t^* = \frac{t}{L_{ref} / U_{ref}}$

where T is temperature. The superscript asterisks (*) denotes the quantity is non-dimensional.

The $dt^*$ used in the input file is non-dimensionalized. To transform $dt^*$  to a time step in real time $dt$ , use this formula:
$dt = \frac{L_{ref} dt^*}{Ma \sqrt(\gamma R T)}$

The dimensions in the mesh are, by consequence of the non-dimensionalization of the variables, also non-dimensional. To transform the dimensions $dx^*$ of the mesh to real dimensions $dx$, use this formula:
$dx = dx^* L_{ref}$

Then, suppose you want to simulate flow past a circular cylinder with diameter $dx = 2 meters$. However, in the mesh you have the diameter is $dx^* = 0.1$ . Then, set 
$L_{ref} = \frac{dx}{dx^*} = \frac{2 meters}{0.1} = 20 meters$

**Comment by jmaximelv** [comment]
Thanks for your very clear reply.  I finally understand that the space coordinates (in the mesh file) like the time step (in the input file) are all non-dimensionalized.

Best regards
Maxime
