### ISSUE TITLE
Dissipation problem

### ISSUE THREAD

**Issue by jmaximelv** [HiFiLES/HiFiLES-solver#57]
Hi all,
I've run a 2D DNS simulation with different mesh resolution and time step. But I found the dissipation of the scheme is a little big. Can anyone give me some suggestions?
I think, for example,  the flux parameters (tau and pen_fact) and the vcjh_scheme_* can influence the dissipation of scheme. But I do not know how to decider those parameters reasonably. 
P.S. the case I'm running can be treat as an aero-acoustics problem.

Thanks in advance
Maxime

**Comment by mlopez14** [comment]
To assist you on this, how are you measuring dissipation?

A good reference on selecting a VCJH (or Energy Stable Flux Reconstruction) scheme is this paper: http://aero-comlab.stanford.edu/Papers/castonguay_cmame_2013.pdf

**Comment by jmaximelv** [comment]
Hi mlopez14,
In fact, I measure the dissipation by my personal intuition  as I found that the shear layer grows too thick in my current case (Direct numerical simulation of automobile cavity tones, CKW Tam et al.) even though I've ensured that the inflow boundary have more than 5-8 cells and that the two successive vortex (2D cylindre case, Re=150, Ma=0.2) have obvious different strength of vorticity.  It's just my personal idea as I fail to get the satisfied results.

Best regards,
Maxime

**Comment by mlopez14** [comment]
Hmm, it sounds like the boundary layer may not be resolved enough. How many elements are you using in the boundary layer, what type of elements do you have there, and what polynomial degree are you using?

**Comment by jmaximelv** [comment]
I've used about 7 cells (quad) in the boundary layer (the thickness of boundary layer expected is 2mm).
I've used both second and third order polynomial.

Best regards
Maxime

**Comment by jmaximelv** [comment]
In fact, I've used  quad cell below y~13mm (it is the 4 times of the height of neck) and tri cell upon that value. As Tam indicated the boundary layer should less than 4mm in order to have the phenomenon found in experiments, I think the space resolution is enough.

Best regards
Maxime

**Comment by mlopez14** [comment]
Here is a neat calculator for finding the width of the element closest to the no-slip boundary. 
http://www.pointwise.com/yplus/
This calculator is intended for 2nd order methods, so multiply whatever width this calculator suggests by (p+1)/2, where p is the degree of the polynomial you are using to approximate the solution.

What width would this calculator suggest for your case? What is the size of the element closest to the no-slip boundary?

**Comment by jmaximelv** [comment]
The width by calculator is 0.00538mm (with y+=1). And what I used in the mesh is 0.18mm. I think it's my fault. I used $\Delta/L \sim \frac{1}{\sqrt{Re}}$ to estimate closest wall mesh size but with L=1m (the real L is 0.00876m).
But what in Tam's article the finest mesh is 0.0825mm, he also uses DNS.

**Comment by mlopez14** [comment]
Then as a rough approximation, the first cell should have a width of 0.00538mm * (p+1)/2 = 0.011mm, where p = 3.

**Comment by jmaximelv** [comment]
The finest grid size is 0.165mm (check again). It need to be more fine. In using HiFiLES, what y+ we should expect?  
Another question about the boundary question: Do you have any suggestions for setting the boundary when the inflow and wall have  intersection? Because this point always cause some problems.

**Comment by mlopez14** [comment]
For your case, the width of the cell closest to the wall should be 0.00538mm * (p+1)/2, where p is the degree of the polynomial used.

Regarding this boundary condition, we have encountered this problem when the mesh is coarse.

I am implementing a stabilization strategy to avoid this problem; it is in the LFS-filters branch. It works on triangular elements exclusively for now.

**Comment by jmaximelv** [comment]
Ok, thanks!

Best regards
Maxime
