### ISSUE TITLE
Questions about Input_file

### ISSUE THREAD

**Issue by yilvqingyan** [HiFiLES/HiFiLES-solver#58]
Could anyone heip me?what's mean of 'sensor and epsion'in the Data Output Options
n_diagnostic_fields: Number of additional calculated fields to output, followed by the names of the fields
Available fields: u v w ... sensor epsion in the Wiki

**Comment by mlopez14** [comment]
These two quantities are related to the shock-capturing scheme implemented for quadrilateral elements.

"Epsilon" is artificial viscosity coefficient values: tells you how much artificial dissipation has been added.
"Sensor" is a quantity that measures the presence of a shock. The higher it is, the more the solution looks like a shock. When you run a simulation with shocks, this quantity gives you an idea about the threshold for applying artificial dissipation.

A more detailed explanation is given in this paper: http://aero-comlab.stanford.edu/Papers/AIAA-Paper_2014-2688.pdf

**Comment by yilvqingyan** [comment]
Hi mlopez14
Thank you very much!
Best regards!
Chen

**Comment by yilvqingyan** [comment]
Hi mlopez14
Thank you very much!
Best regards!
Chen

**Comment by yilvqingyan** [comment]
Hi
I have another problm.Could you help me?In the case of cylinder,the input_file in the file of euler:"Re_c_ic is 100,u_c-ic is 1 nx_free_stream is 1...",the input_file in the file of Navier-Stokes:Re_c_ic is 20,u_c_ic is 1 nx_free_stream is 1..." my question is that The "Re" varied ,why is the "u_c_ic and nx_free_stream" the same?because Re=(UD)/v,I hope that I describe my question.
Best regards!
Chen

**Comment by yilvqingyan** [comment]
Hi
I have another problm.Could you help me?In the case of cylinder,the input_file in the file of euler:"Re_c_ic is 100,u_c-ic is 1 nx_free_stream is 1...",the input_file in the file of Navier-Stokes:Re_c_ic is 20,u_c_ic is 1 nx_free_stream is 1..." my question is that The "Re" varied ,why is the "u_c_ic and nx_free_stream" the same as 1?because Re=(UD)/v,I hope that I describe my question,clearly.
Best regards!
Chen

**Comment by mlopez14** [comment]
nx_free_stream is just the x-component of the unit vector of the direction of the free stream flow.

nx_free_stream = 1 and ny_free_stream=1 would give you a free stream at 45 degrees above the x-axis.

The actual speed of the flow is set from the Mach number. Reynolds number determines the density of the flow based on the values of viscosity and reference length you give.

We'll create a tutorial on the non-dimensionalization of the equations shortly.

In the meantime, this answer should be useful: https://github.com/HiFiLES/HiFiLES-solver/issues/55

**Comment by yilvqingyan** [comment]
Hi mlopez14
Thank you very much for your help.I understand it in some extent and I will strive for it!
Best regards!
chen

**Comment by yilvqingyan** [comment]
Hi mlopez14
Could you heip me?How to output the file of Cd and Cl.I read the eles.cpp in 6088:"//Need to add a reference area to the input file...Not needed for Cp/Cf." I don't understand that.I know that the Cp.dat output in the force_files.
Thank you very much.
Sincerely.
Chen.
