### ISSUE TITLE
About 2D Taylor-Green Vortex

### ISSUE THREAD

**Issue by arctanx** [HiFiLES/HiFiLES-solver#59]
Hi all,
I tried to run a 2D Taylor-Green Vortex case with the initial conditions originally given at line 555 (Simple 2D div-free vortex) in eles.cpp. The input file was the one provided for the 3D TGV test case. The 2D triangular mesh was generated using Gmsh. The problem is that I kept running into the "Fatal error 'NaN in residual, exiting.' at ../src/eles.cpp:1681" after writing Tecplot file number 0. Could anyone shed a light on what I should do to get it running?
Thanks in advance!
Best Regards
arctanx

**Comment by mlopez14** [comment]
Perhaps the time-step size is too large. What time-step and polynomial order are you using?

**Comment by arctanx** [comment]
I've tried time-step size as small as 1E-9, and the polynomial order down to 1, still not working.

**Comment by mlopez14** [comment]
You've found a bug! Pressure is being initialized to zero. See line 556 in eles.cpp. I'll make the quick change and let you know when it's ready.

**Comment by mlopez14** [comment]
Fixed! Let us know if it works now. Remember to pull the latest change.

**Comment by arctanx** [comment]
It is working now! Thanks a lot. I should have noticed the bug.

**Comment by mlopez14** [comment]
Thanks for reporting it!
