### ISSUE TITLE
A Critical Problem in Memory Scalability 

### ISSUE THREAD

**Issue by ramezaniua** [HiFiLES/HiFiLES-solver#6]
I tried it with BLAS=NO and parmetis=YES and OpenMPI.
In Cylinder test case It took ~7M of memory for serial but in Parallel each processor took near to 10M of memory (It is supposed 7M must be divided to number of processor) and it exactly opposite of memory scalaibility.

**Comment by mlopez14** [comment]
@ramezaniua, I am suspecting this has something to do with ParMetis's overhead. Here is a report at the ParMetis's forum describing a similar situation: http://glaros.dtc.umn.edu/gkhome/node/1071

We would have to look at how they are handling the mesh partitioning. On the solver's end, there is no new memory allocation after the mesh is partitioned.

Let us know if you find a solution to the ParMetis memory scalability issue; we'll look into it as well and report back.
