### ISSUE TITLE
msh file after parmetis , boudnary face somtimes not found!

### ISSUE THREAD

**Issue by fff969** [HiFiLES/HiFiLES-solver#60]
I  use ICEM to gen CGNS file and then  use my won programe  convertting the CGNS file to msh file. 
When I run HiFiLES (GPU version) on one processor  everything is OK ( see Pic 1) but when I run
HiFiLES with mpich ( mpiexec -n X HiFiLES input_file)  for some cases the programe will stop when 
run at the Line 1511 in geometry.cpp file with the hint " All nodes of boudnary face belong to 
processor but could not find the Corresponding faces " (see Pic 2 and Pic 3). what wrong ?  
   Another question, When I use the mutil-GPU host , there only one GPU wroks even runing with the
 mpiexec command.  Are there some solutions for the HFiLES run on different GPUs.  
 
![single](https://cloud.githubusercontent.com/assets/10339313/7703640/e7ad8f30-fe6b-11e4-97fa-1b4938c6402b.png)
![mpi-2](https://cloud.githubusercontent.com/assets/10339313/7703643/eda1d3f6-fe6b-11e4-80ed-4daf9cb86c95.png)
![mpi-2-1](https://cloud.githubusercontent.com/assets/10339313/7703647/f598f878-fe6b-11e4-8a6f-df1862532920.png)

**Comment by mlopez14** [comment]
I suspect there is some issue with MPI. Either it is not installed properly in your machine or we have incompatibility issues with your specific version.

Can you run one of the testcases in multiple GPUs? Say the viscous cylinder case under testcases/navier-stokes/cylinder .

To run on multiple GPUs follow the instructions here: https://github.com/HiFiLES/HiFiLES-solver/wiki/Execution

Yes, we run HiFiLES all the time in many GPUs at a time.

**Comment by fff969** [comment]
Dear mlopez,
 Thank you for your patient. 
   I try many cases for the parmetis problems. and found that .For hexa meshes everthing is OK. But for the tetra meshes. the error  appear  at  most times. I thought there may be some bugs in the functions about msh files for tetra meshes. I  don'tknow anything about gambit so I can't test the neu files. 
  for the second questions. I have read the guideline which you list on your post carefully and still don't konw what happend to me .  I have run HiFiLES mpiexec -n 4 HiFiLES input_file but still only one GPU used  ( please see pic.). By the way I use MPICH instead of the MPICH2 ,is this the reason ?
![screenshot from 2015-05-21 20 02 14](https://cloud.githubusercontent.com/assets/10339313/7748199/e415f62c-ffb1-11e4-834a-2f868884bede.png)

**Comment by fff969** [comment]
Dear mlopez,
 Thank you for your patient. 

  For the irst problems I have mentioned, I try many cases for the parmetis problems. and found that .For hexa meshes everthing is OK. But for the tetra meshes. the error  appear  at  most times. I thought there may be some bugs in the functions about msh files for tetra meshes. I  don'tknow anything about GAMBIT so I can't test the "neu" files. 

  For the second questions. I have read the guideline which you list on your post carefully and still don't konw what happend to me .  I have run HiFiLES mpiexec -n 4 HiFiLES input_file but still only one GPU used  ( please see pic.). By the way I use MPICH instead of the MPICH2 ,is this the reason ?

![Uploading Screenshot.png…]()

**Comment by fff969** [comment]
Dear mlopez,
 Thank you for your patient. 

  For the irst problems I have mentioned, I try many cases for the parmetis problems. and found that .For hexa meshes everthing is OK. But for the tetra meshes. the error  appear  at  most times. I thought there may be some bugs in the functions about msh files for tetra meshes. I  don'tknow anything about GAMBIT so I can't test the "neu" files. 

  For the second questions. I have read the guideline which you list on your post carefully and still don't konw what happend to me .  I have run HiFiLES mpiexec -n 4 HiFiLES input_file but still only one GPU used  ( please see pic.). By the way I use MPICH instead of the MPICH2 ,is this the reason ?

![Uploading Screenshot.png…]()

**Comment by mlopez14** [comment]
Double check the instructions here https://github.com/HiFiLES/HiFiLES-solver/wiki/Execution
You will need to create a machine file and run the code with
''mpirun -n 5 -machinefile mfile ./HiFiLES input_file''

The contents of this mfile are described in the instructions.

**Comment by mlopez14** [comment]
Regarding MPI, I suggest re-installing it. We have used many kinds of MPI and they all work. The MPI commands used in the code are the basic ones like send receive collect. Can you run other parallel codes with your MPI?  The other option is that you have not compiled the code with MPI. Can you mention the contents of your configure_run.sh file?

**Comment by JacobCrabill** [comment]
We actually just realized there is a small bug in the code - the fix has been pushed to master now, so try the latest version.  Basically, we had hard-coded the ID's in cudaSetDevice(device_id) for the machines we use in our lab here, and did not account for the possibility of others machines / clusters using the multi-GPU feature.  

So what was happening in your case was that each process launched by mpirun was using the same CUDA device, because they didn't know better. The fix is for each process to call cudaSetDevice() and give it a unique CUDA device ID (separate from the other processes).  

If you are still having issues, figure out the cuda device ID's of your GeForce cards and hard-code them into HiFiLES - the relevant line is line 111 of geometry.cpp in the current commit (https://github.com/HiFiLES/HiFiLES-solver/commit/08b53e1f9889878a353f7e148c32d75eb1c16d7c).  Let us know if this fixes your problem!

**Comment by fff969** [comment]
Thank you very much  Jacob . Your patch have already fixed this bug. 


-----原始邮件-----
发件人: "Jacob Crabill" <notifications@github.com>
发送时间: ‎2015/‎5/‎22 8:09
收件人: "HiFiLES/HiFiLES-solver" <HiFiLES-solver@noreply.github.com>
抄送: "fff969" <fff969@126.com>
主题: Re: [HiFiLES-solver] msh file after parmetis , boudnary face somtimesnot found! (#60)

We actually just realized there is a small bug in the code - the fix has been pushed to master now, so try the latest version. Basically, we had hard-coded the ID's in cudaSetDevice(device_id) for the machines we use in our lab here, and did not account for the possibility of others machines / clusters using the multi-GPU feature. 
So what was happening in your case was that each process launched by mpirun was using the same CUDA device, because they didn't know better. The fix is for each process to call cudaSetDevice() and give it a unique CUDA device ID (separate from the other processes). 
If you are still having issues, figure out the cuda device ID's of your GeForce cards and hard-code them into HiFiLES - the relevant line is line 111 of geometry.cpp in the current commit (08b53e1). Let us know if this fixes your problem!

**Comment by fff969** [comment]
I have already fixed this bug ,  I input the card number manually
