### ISSUE TITLE
Help for Inupt_file

### ISSUE THREAD

**Issue by yilvqingyan** [HiFiLES/HiFiLES-solver#62]
Hi
Could anybody heip me?How to output the file of Cd and Cl.I read the eles.cpp in 6088:"//Need to add a reference area to the input file...Not needed for Cp/Cf."but I don't understand that.
Sincerely.
Chen.

**Comment by mlopez14** [comment]
The values of C_d and C_l can be found in the history.plt file. They are output every time the residual is output. The  headers in the file tell you which quantity is which.

**Comment by yilvqingyan** [comment]
Hi
Thank you very much.I have read the file.but there are always some error in the history.plt file in different case or in different condition in the same case.sometimes,in the line 23 or others.Don't open by Tecplot.I don't know why.Could you explain the reason?
sincerely.
Chen

**Comment by mlopez14** [comment]
It is currently not outputting properly formatted for Tecplot. As a
workaround, I have been removing the first two lines and reading the file
using the 'load' function in Matlab.

**Comment by yilvqingyan** [comment]
Thank you very much.
Sincerely.
chen
