### ISSUE TITLE
Questions about two inlets with different velocities

### ISSUE THREAD

**Issue by popstar0426** [HiFiLES/HiFiLES-solver#64]
Hi:
 
   Consider a T-Junction (pipe system), there are two inlets with different velocities and temperatures.
   How to set boundary conditions for such a case?

Best regards!
Yue

**Comment by popstar0426** [comment]
Hi:

  songthing like this (T-Junction in channel)

**Comment by JacobCrabill** [comment]
Hi Yue,

Unfortunately, that kind of boundary-condition assignment is not supported as-is in the code. However, it would be relatively simple to implement yourself.  Here's the steps to do so:

1. Create a copy of the boundary condition you want to implement within "bdy_inters::set_inv_boundary_conditions()" (bdy_inters.cpp, starting at line 391) which uses a different set of boundary-condition values (you could just hard-code these if you like, or setup additional variables in input.cpp)
2. Add a new entry in geometry.cpp lines 121-147, "get_bc_number(string& bcname)"; both the string and the integer must be unique, and the integer must match the one used in your new boundary condition in bdy_inters.cpp

That should do it, I think; let us know if you need any help!

-Jacob
