### ISSUE TITLE
Problems about solutiontime in tecplot when I use globa CFL as the time-advance type 

### ISSUE THREAD

**Issue by javierchang** [HiFiLES/HiFiLES-solver#68]
Hi, 

After I specified the dt_type=1 and specifies the CFL number(=1 in my case), I can run my case smoothly, but when I check a sequence of tecplot output file(.plt) to examine my flow field, I found all the solutiontime in tecplot output file equals 0, which translates into my inability to make an animation with the this sequence of files, unless I artificially change the solutiontime(of course is a demading task since there are a lot of output files and I do not know the exact flow time).

But when I specified the dt_type=0 and specifies dt(=1e-7 in my case), it turns out the solutiontime in tecplot output file is correct and equals the flow time in calculation(which is not 0 as the above case).

So I read 'eles.cpp' and find this:
if (run_input.dt_type == 0)
      dt = run_input.dt;
    else if (run_input.dt_type == 1)
      dt = dt_local(0);
which means the value of dt_local has already been passed to dt and if it worked,hypothetically, the solutiontime would by no means equal 0 when I specify CFL. 

Therefore, I need some help regarding this problems so that I am able to know the every flow time when I specify global CFL in time advancement.

Thanks!

**Comment by mlopez14** [comment]
I think this issue was solved a few weeks ago; @JacobCrabill will need to confirm.

**Comment by JacobCrabill** [comment]
I believe I found the issue; the variable "FlowSol->time" was only updated using the user-specified "run_input.dt"; I have now modified the time-advance function to change that "dt" value to the new value at each iteration so that the output time will be the correct physical flow time.
