### ISSUE TITLE
Boundary conditions for Taylor_Green_Vortex

### ISSUE THREAD

**Issue by popstar0426** [HiFiLES/HiFiLES-solver#69]
Hi:

   I am studying the testcase "Taylor_Green_Vortex".
   I am confused with the BCs. There is only "Cyclic" boundary condition in the filed.
   What is the input boundary condition?
   
   
Best regards!

**Comment by mlopez14** [comment]
In this test case there is no need for additional boundary conditions. The initial conditions dictate the direction of the movement of the vortex. The cyclic boundary conditions act as inflow or outflow based on the characteristics of the solution.
