### ISSUE TITLE
Turbulent spots on a flat plate in supersonic flow

### ISSUE THREAD

**Issue by sree-kanth** [HiFiLES/HiFiLES-solver#71]
Hi

I have downloaded the solver and have had a look at the features available in the code. From the 2014 AIAA paper, I understand that a well-resolved boundary layer over a flat plate could be generated at subsonic speeds. I was wondering if you think it is possible to use this code to model the boundary layer over a flat plate at super/hypersonic Mach numbers and observe the growth of turbulent spots in a transitional boundary layer in 3D? If yes, could you please give some inputs as to how I could go about implementing it. I would like to generate both discrete/isolated spots using a pulsed disturbance wave as well as let the flow naturally transition to turbulent flow via the mechanism of spot formation - Q-criterion visualization (as you've reported in the paper) could be one of the ways to visualize spots. 

Looking forward to hearing back from you! Thanks.

Warm regards,
Sree.

**Comment by mlopez14** [comment]
Hi Sree, 

I think this would certainly be possible. A major hurdle would be capturing the shock. I am in the process of implementing what we call Local Fourier Filters, so the solution can be stabilized in all dimensions and all elements. The changes should be pushed to the main branch in the coming week or two.

The main work you would need to do is to implement the application of pulsed disturbances. To implement this, I suggest you take a look at the function 
`void eles::AdvanceSolution(int in_step, int adv_type)`
here all conservation fields are updated directly. If you prefer to pose the disturbances as a forcing term, take a look at
`evaluate_viscFlux` and `evaluate_invFlux`.

Let us know if you encounter any problems or roadblocks.

**Comment by sree-kanth** [comment]
Thanks a lot for your response and indicating where I should look in the code to be able to possibly implement some of the things that are needed to get this working!

I was wondering if we can actually look at the BL region alone (with flow that has already been shock-treated), so that we won't need to worry about capturing the shock at all - like how some of the DNS people do it. We may need to initialize the domain with an NS solution from another code that has shock capturing features, and use that as a starting point. Else, if we know what conditions are expected behind the shock (from shock relations, for eg.), a priori, and if we could use that, that would also be great. Anyways, if the Local Fourier Filters implementation is going to sort out this issue, then I'd be happy to wait for a couple of weeks, while I can have a look at the other areas of the code (to implement pulsed disturbances etc.). 

Please let me know what you think. Thanks again!

Warm regards,
Sree.

**Comment by sree-kanth** [comment]
Sorry: ****We may need to initialize the domain with an "RANS" solution from another code.

**Comment by mlopez14** [comment]
Hmm, we have looked into adding the functionality of starting with a different flow condition. The current workaround is to create a "restart" file with the desired initial conditions.

The Local Fourier Filters are working now in the LFS-filters branch with triangular elements exclusively. I imagine you would want to run this simulation with hexahedral elements, correct?

**Comment by sree-kanth** [comment]
Thanks! Yes, hex would be ideal, especially because it is just for simple geometries to start with (like flat plates) and the BL region is what I am most interested in.
