### ISSUE TITLE
Question about the coordinate transformation

### ISSUE THREAD

**Issue by jmaximelv** [HiFiLES/HiFiLES-solver#72]
Hi all,
I'm confused by the coordinate for a while. In fact, I cannot find the explicit coordinate mapping where I think it should have one. 
For example, after a time step advancing, the results stored in "disu_upts" should be solutions at physical space (as it has  "rhs = -div_tconf_upts(0)(inp,ic,i)/detjac_upts(inp,ic)+..." in the time advance method and it was used directly for output (method calc_disu_ppts)). But when "disu_upts" were used for the FR procedure, like in the computation of  "disuf_upts" (calc_sgs_terms), I can not find the procedure that transform explicit the solution from phy. space to comp. space!
Hope someone can help me figure out of that.
Thanks in advance!

Best regards,
Maxime

**Comment by mlopez14** [comment]
Good questions! The mapping from the computational domain to the physical domain really happens through the formulation of the fluxes, as seen in the way the inviscid fluxes (`evaluate_invFlux`) and the viscous fluxes (`evaluate_viscFlux`) are evaluated. You will notice that the variable `JGinv_dyn_upts` is used before the Riemann solver is called.

The mapping from the computational domain to the physical domain is completed when the residual is divided by the Jacobian at the solution point.

Nevertheless, the values of `disu_upts` ("discontinuous solution u at solution points") are always physical, as the mapping between physical and computational domain only affects the location of the solution values, not the solution values themselves. The values of the derivatives of the solution  are affected by the mapping.

Let us know if I haven't cleared your doubt completely.

**Comment by jmaximelv** [comment]
Hi Lopez,
Thank you very sincerely. I think I've well understood the mapping process in HiFi. 
Thanks again.

Sincerely,
Maxime
