### ISSUE TITLE
Question about 2D wake vortex simulation

### ISSUE THREAD

**Issue by arctanx** [HiFiLES/HiFiLES-solver#79]
Hi all,
I tried to run a 2D wake vortex case of fixed wing airplane. The wake vortex is initiated with a pair of Lamb-Oseen vortex. The code was implementated in a way similar to the TGV case. The problem is that the vortices diffuse quickly after several hundred of steps. The density in the vortex core region also decreses to a small value. I'm confused since the vortices are supposed to last for a long time and the density should be constant. Should I run this case with an incompressible solver?
Thanks!

**Comment by mlopez14** [comment]
I'm not too familiar with the case of the Lamb-Oseen vortex. However, by looking at the analysis performed by Saffman in the book "Vortex Dynamics" (Saffman, P. G.. Vortex Dynamics. 1st ed. Cambridge: Cambridge University Press, 1993. Cambridge Books Online. Web. 09 July 2015. http://dx.doi.org/10.1017/CBO9780511624063) in page 262, equation 24, pressure is shown to be proportional to time raised to a negative integer. Equation 26 shows that the axial velocity is also proportional to time raised to a negative integer.

This would lead me to believe that the vortex is supposed to dissipate somewhat quickly. I don't know how large your time steps are, so if they're tiny, I would agree that just after hundreds of iterations the vortex should not dissipate.

Nevertheless, I would suggest increasing the resolution of the grid. As a quick check, try increasing the value of p as well.

Also, I would suggest double checking that you're using the RK45 time-stepping scheme.

**Comment by mlopez14** [comment]
I'm curious, how did this go?
