### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by amihaisilver** [HiFiLES/HiFiLES-solver#8]
Dear support, 

I try to install the HiFiLES on a RedHat cluster with mpich, but the installation failed with the error below. 

the system is : 
Red Hat Enterprise Linux Server release 6.4 (Santiago)
Linux tamnun 2.6.32-358.23.2.el6.x86_64 #1 SMP Sat Sep 14 05:32:37 EDT 2013 x86_64

Attached are the installation logs. 
I appreciate your help. 

make[1]: Entering directory `/usr/local/HiFiLES-solver-master/obj'
  CXX    ../src/___bin_HiFiLES-global.o
g++: 1.0.0": No such file or directory
<command-line>: warning: missing terminating " character
make[1]: *** [../src/___bin_HiFiLES-global.o] Error 1
make[1]: Leaving directory `/usr/local/HiFiLES-solver-master/obj'
make: *** [all-recursive] Error 1

The full installation log is below
Thanks, 
Amihai

cat configure_run.sh

#####################################################
# \file configure_run.sh
# \brief Configuration script for HiFiLES
# \author - Original code: SD++ developed by Patrice Castonguay, Antony Jameson,
#                          Peter Vincent, David Williams (alphabetical by surname).
#         - Current development: Aerospace Computing Laboratory (ACL)
#                                Aero/Astro Department. Stanford University.
# \version 0.1.0
#
# High Fidelity Large Eddy Simulation (HiFiLES) Code.
# Copyright (C) 2014 Aerospace Computing Laboratory (ACL).
#
# HiFiLES is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# HiFiLES is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with HiFiLES.  If not, see <http://www.gnu.org/licenses/>.
#####################################################
# Standard (Helpful) Settings [Should not need to change these]
export HIFILES_HOME=$(pwd)
# ---------------------------------------------------------------
# Basic User-Modifiable Build Settings [Change these as desired]
NODE="CPU"              # CPU or GPU
CODE="RELEASE"            # DEBUG or RELEASE
BLAS="ATLAS"               # ATLAS, STANDARD, ACCLERATE, or NO
PARALLEL="YES"           # YES or NO
TECIO="NO"              # YES or NO
METIS="YES"              # Build & link to the HiFiLES-supplied ParMETIS libraries? YES or NO
# ---------------------------------------------------------------
# Compiler Selections [Change compilers or add full filepaths if needed]
CXX="g++"               # C++ compiler - Typically g++ (default, GNU) or icpc (Intel)
NVCC="nvcc"             # NVidia CUDA compiler
MPICC="mpicxx"          # MPI C compiler
# ---------------------------------------------------------------
# Library & Header File Locations [Change filepaths as needed]
BLAS_LIB="/usr/lib64/atlas"
BLAS_INCLUDE="/usr/include/atlas-x86_64-base"

TECIO_LIB="lib/tecio-2008/lib"
TECIO_INCLUDE="lib/tecio-2008/include"

CUDA_LIB="/usr/local/cuda/lib64"
CUDA_INCLUDE="/usr/local/cuda/include"

# If building the supplied ParMETIS libraries, need the MPI header location
MPI_INCLUDE="/usr/include/mpich2-x86_64"       # location of mpi.h
#MPI_INCLUDE="/usr/include/openmpi-x86_64"       # location of mpi.h

# If NOT building the supplied ParMetis library, location of installed libraries
PARMETIS_LIB="/usr/local/lib"           # location of libparmetis.a
PARMETIS_INCLUDE="/usr/local/include"   # location of parmetis.h

METIS_LIB="/usr/local/lib"              # location of libmetis.a
METIS_INCLUDE="/usr/local/include"      # location of metis.h

# ---------------------------------------------------------------
# Run configure using the chosen options [Should not change this]
if [[ "$NODE" == "GPU" ]]
then
    _GPU=$NVCC
else
    _GPU="NO"
fi
if [[ "$PARALLEL" == "YES" ]]
then
    _MPI=$MPICC
else
    _MPI="NO"
    PARMETIS_LIB="NO"
    PARMETIS_INCLUDE="NO"
fi
if [[ "$TECIO" == "NO" ]]
then
    TECIO_LIB="NO"
    TECIO_INCLUDE="NO"
fi
./configure --prefix=$HIFILES_RUN/.. \
            --with-CXX=$CXX \
            --with-BLAS=$BLAS \
            --with-BLAS-lib=$BLAS_LIB \
            --with-BLAS-include=$BLAS_INCLUDE \
            --with-MPI=$_MPI \
            --with-MPI-include=$MPI_INCLUDE \
            --with-CUDA=$_GPU \
            --with-CUDA-lib=$CUDA_LIB \
            --with-CUDA-include=$CUDA_INCLUDE \
            --with-ParMetis-lib=$PARMETIS_LIB \
            --with-ParMetis-include=$PARMETIS_INCLUDE \
            --with-Metis-lib=$METIS_LIB \
            --with-Metis-include=$METIS_INCLUDE \
            --with-Tecio-lib=$TECIO_LIB \
            --with-Tecio-include=$TECIO_INCLUDE \
            --enable-metis=$METIS

[root@tamnun HiFiLES-solver-master]# ./configure_run.sh
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
<<< Configuring library with Metis support >>>
./configure: line 3027: AX_TLS: command not found
checking for /usr/lib64/atlas/libcblas.a... yes
checking for /usr/lib64/atlas/libatlas.a... yes
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether mpicxx accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of mpicxx... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking whether gcc and cc understand -c and -o together... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1966080
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... mpicxx -E
checking for ld used by mpicxx... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the mpicxx linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for mpicxx option to produce PIC... -fPIC -DPIC
checking if mpicxx PIC flag -fPIC -DPIC works... yes
checking if mpicxx static flag -static works... no
checking if mpicxx supports -c -o file.o... yes
checking if mpicxx supports -c -o file.o... (cached) yes
checking whether the mpicxx linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
configure: creating ./config.status
config.status: creating lib/parmetis-4.0.2/Makefile
config.status: creating lib/parmetis-4.0.2/metis/Makefile
config.status: creating Makefile
config.status: creating lib/Makefile
config.status: creating obj/Makefile
config.status: executing depfiles commands
config.status: executing libtool commands

Build Configuration Summary:

    Source code location: /usr/local/HiFiLES-solver-master
    Install location: 	  /
    Version:              1.0.0
    Compiler:             mpicxx
    Preprocessor flags:   
    Compiler flags:        -D_MPI
    Linker flags:         
    BLAS support:         YES
    MPI support:          YES
    CUDA support:         NO
    TecIO support:        NO

# make
Making all in lib
make[1]: Entering directory `/usr/local/HiFiLES-solver-master/lib'
Making all in parmetis-4.0.2/
make[2]: Entering directory `/usr/local/HiFiLES-solver-master/lib/parmetis-4.0.2'
Making all in metis/
make[3]: Entering directory `/usr/local/HiFiLES-solver-master/lib/parmetis-4.0.2/metis'
  CC     GKlib/libmetis_a-b64.o
  CC     GKlib/libmetis_a-blas.o
  CC     GKlib/libmetis_a-csr.o
  CC     GKlib/libmetis_a-error.o
  CC     GKlib/libmetis_a-evaluate.o
  CC     GKlib/libmetis_a-fkvkselect.o
  CC     GKlib/libmetis_a-fs.o
  CC     GKlib/libmetis_a-getopt.o
  CC     GKlib/libmetis_a-gkregex.o
  CC     GKlib/libmetis_a-htable.o
  CC     GKlib/libmetis_a-io.o
  CC     GKlib/libmetis_a-itemsets.o
  CC     GKlib/libmetis_a-mcore.o
  CC     GKlib/libmetis_a-memory.o
  CC     GKlib/libmetis_a-omp.o
  CC     GKlib/libmetis_a-pdb.o
  CC     GKlib/libmetis_a-pqueue.o
  CC     GKlib/libmetis_a-random.o
  CC     GKlib/libmetis_a-seq.o
  CC     GKlib/libmetis_a-sort.o
  CC     GKlib/libmetis_a-string.o
GKlib/string.c: In function ‘gk_str2time’:
GKlib/string.c:506: warning: comparison between pointer and integer
  CC     GKlib/libmetis_a-timers.o
  CC     GKlib/libmetis_a-tokenizer.o
  CC     GKlib/libmetis_a-util.o
  CC     libmetis/libmetis_a-auxapi.o
  CC     libmetis/libmetis_a-balance.o
  CC     libmetis/libmetis_a-bucketsort.o
  CC     libmetis/libmetis_a-checkgraph.o
  CC     libmetis/libmetis_a-coarsen.o
  CC     libmetis/libmetis_a-compress.o
  CC     libmetis/libmetis_a-contig.o
  CC     libmetis/libmetis_a-debug.o
  CC     libmetis/libmetis_a-fm.o
  CC     libmetis/libmetis_a-fortran.o
  CC     libmetis/libmetis_a-frename.o
  CC     libmetis/libmetis_a-gklib.o
  CC     libmetis/libmetis_a-graph.o
  CC     libmetis/libmetis_a-initpart.o
  CC     libmetis/libmetis_a-kmetis.o
  CC     libmetis/libmetis_a-kwayfm.o
  CC     libmetis/libmetis_a-kwayrefine.o
  CC     libmetis/libmetis_a-mcutil.o
  CC     libmetis/libmetis_a-mesh.o
  CC     libmetis/libmetis_a-meshpart.o
  CC     libmetis/libmetis_a-minconn.o
  CC     libmetis/libmetis_a-mincover.o
  CC     libmetis/libmetis_a-mmd.o
  CC     libmetis/libmetis_a-ometis.o
  CC     libmetis/libmetis_a-options.o
  CC     libmetis/libmetis_a-parmetis.o
  CC     libmetis/libmetis_a-pmetis.o
  CC     libmetis/libmetis_a-refine.o
  CC     libmetis/libmetis_a-separator.o
  CC     libmetis/libmetis_a-sfm.o
  CC     libmetis/libmetis_a-srefine.o
  CC     libmetis/libmetis_a-stat.o
  CC     libmetis/libmetis_a-timing.o
  CC     libmetis/libmetis_a-util.o
  CC     libmetis/libmetis_a-wspace.o
  AR     libmetis.a
make[3]: Leaving directory `/usr/local/HiFiLES-solver-master/lib/parmetis-4.0.2/metis'
make[3]: Entering directory `/usr/local/HiFiLES-solver-master/lib/parmetis-4.0.2'
  CC     libparmetis/libparmetis_a-akwayfm.o
  CC     libparmetis/libparmetis_a-ametis.o
  CC     libparmetis/libparmetis_a-balancemylink.o
  CC     libparmetis/libparmetis_a-comm.o
  CC     libparmetis/libparmetis_a-csrmatch.o
  CC     libparmetis/libparmetis_a-ctrl.o
  CC     libparmetis/libparmetis_a-debug.o
  CC     libparmetis/libparmetis_a-diffutil.o
  CC     libparmetis/libparmetis_a-frename.o
  CC     libparmetis/libparmetis_a-gkmetis.o
  CC     libparmetis/libparmetis_a-gkmpi.o
  CC     libparmetis/libparmetis_a-graph.o
  CC     libparmetis/libparmetis_a-initbalance.o
  CC     libparmetis/libparmetis_a-initmsection.o
  CC     libparmetis/libparmetis_a-initpart.o
  CC     libparmetis/libparmetis_a-kmetis.o
  CC     libparmetis/libparmetis_a-kwayrefine.o
  CC     libparmetis/libparmetis_a-match.o
  CC     libparmetis/libparmetis_a-mdiffusion.o
  CC     libparmetis/libparmetis_a-mesh.o
  CC     libparmetis/libparmetis_a-mmetis.o
  CC     libparmetis/libparmetis_a-move.o
  CC     libparmetis/libparmetis_a-msetup.o
  CC     libparmetis/libparmetis_a-node_refine.o
  CC     libparmetis/libparmetis_a-ometis.o
  CC     libparmetis/libparmetis_a-pspases.o
  CC     libparmetis/libparmetis_a-redomylink.o
  CC     libparmetis/libparmetis_a-remap.o
  CC     libparmetis/libparmetis_a-renumber.o
  CC     libparmetis/libparmetis_a-rmetis.o
  CC     libparmetis/libparmetis_a-selectq.o
  CC     libparmetis/libparmetis_a-serial.o
  CC     libparmetis/libparmetis_a-stat.o
  CC     libparmetis/libparmetis_a-timer.o
  CC     libparmetis/libparmetis_a-util.o
  CC     libparmetis/libparmetis_a-wave.o
  CC     libparmetis/libparmetis_a-weird.o
  CC     libparmetis/libparmetis_a-wspace.o
  CC     libparmetis/libparmetis_a-xyzpart.o
  AR     libparmetis.a
make[3]: Leaving directory `/usr/local/HiFiLES-solver-master/lib/parmetis-4.0.2'
make[2]: Leaving directory `/usr/local/HiFiLES-solver-master/lib/parmetis-4.0.2'
Making all in parmetis-4.0.2/metis
make[2]: Entering directory `/usr/local/HiFiLES-solver-master/lib/parmetis-4.0.2/metis'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/HiFiLES-solver-master/lib/parmetis-4.0.2/metis'
make[2]: Entering directory `/usr/local/HiFiLES-solver-master/lib'
make[2]: Nothing to be done for `all-am'.
make[2]: Leaving directory `/usr/local/HiFiLES-solver-master/lib'
make[1]: Leaving directory `/usr/local/HiFiLES-solver-master/lib'
Making all in obj
make[1]: Entering directory `/usr/local/HiFiLES-solver-master/obj'
  CXX    ../src/___bin_HiFiLES-global.o
g++: 1.0.0": No such file or directory
<command-line>: warning: missing terminating " character
make[1]: *** [../src/___bin_HiFiLES-global.o] Error 1
make[1]: Leaving directory `/usr/local/HiFiLES-solver-master/obj'
make: *** [all-recursive] Error 1

**Comment by mlopez14** [comment]
Sorry for the delay in the response; we were taken aback by the length of the message.

It seems to be a problem with how automake configured your compilation. Perhaps your compiler is not g++ but rather gcc or the like.

When you type g++ in your command line, do you get a message saying the command is non-existent?
