### ISSUE TITLE
memory required in HiFiLES

### ISSUE THREAD

**Issue by popstar0426** [HiFiLES/HiFiLES-solver#80]
Hi:
  How to estimate the memory requirement for a case in HIFILES?

Best regards!

**Comment by popstar0426** [comment]
Hi:
   What is the relations between cells and DOFs?
   In my thought, in a 4th order  3D simulation, DOFs shall be 64 times of hexahedral cells.
   However, is there any detail relation (list) between mesh type, polynomial degree, number of cells and DOFs?
   What is relation between DOFs and memory requirement in HiFiLES?

Best regards!

**Comment by mlopez14** [comment]
I would refer you to this paper where the number of DoFs is tabulated with the element type as a function of the polynomial order: http://arc.aiaa.org/doi/abs/10.2514/6.2015-2447

We'll have to get back to you on the memory requirements; it's more involved to get this estimate than we thought.
