### ISSUE TITLE
How to set ATLAS in ubuntu 14.04?

### ISSUE THREAD

**Issue by popstar0426** [HiFiLES/HiFiLES-solver#81]
Hi:
   In configure_run.sh, there is BLAS setting.
   Question: How do I install ATLAS in ubuntu 14.04?
   How to use it in HiFiLES?

Best regards!

**Comment by mlopez14** [comment]
I found this guide to install ATLAS here: https://bazaar.launchpad.net/~ubuntu-branches/ubuntu/trusty/atlas/trusty/view/head:/debian/README.Debian

To use it, go to the configure_run.sh file and set line 32 to
```
BLAS="ATLAS"
```
then reconfigure the compilation by typing the command
```
./configure_run.sh
```
followed by
```
make -j
```
(the -j option accelerates compilation by using all available processors).

**Comment by mlopez14** [comment]
I have just created a brief tutorial on the ATLAS installation in Ubuntu here: https://github.com/HiFiLES/HiFiLES-solver/wiki/Installing-ATLAS-in-Ubuntu
