### ISSUE TITLE
paraview can not read HiFiLES 's output file

### ISSUE THREAD

**Issue by popstar0426** [HiFiLES/HiFiLES-solver#82]
Hi:
  I met an error when I do postprocessing of HiFiLES results.
  The error is :ERROR: In /home/kitware/Dashboards/MyTests/NightlyMaster/ParaViewSuperbuild-Release/paraview/src/paraview/VTK/IO/XML/vtkXMLPDataReader.cxx, line 364
vtkXMLPUnstructuredGridReader (0x3733d50): File for piece 0 cannot be read.
  Have you met this before?

Best regards!

**Comment by mlopez14** [comment]
No, we have not. What types of elements were in the mesh and what were the
output diagnostic fields?

Was the output file human readable? (It should be an XML file)

**Comment by popstar0426** [comment]
hi:
I downloaded a new copy of hifiles. When I run the flatplate case in navier-stokes drectory, I met this error. I did not met this problem before.

**Comment by jrbull** [comment]
This problem is encountered when the vtu is corrupted or missing from the directory where it should be written. That may or may not be the fault of HiFiLES. Is the problem reproducible on different computers/numbers of processors/test cases? As Manuel said, if the file is corrupted, it may contain non-human-readable strings when opened in a text editor.

Postdoctoral Scholar
Dept of Aero/Astro Engineering
Stanford University

**Comment by popstar0426** [comment]
Hi:
  I have found the solution.
  The error is caused by the different name of mesh file and output file.
   The name of mesh is always Mesh000....
    If you give the output file as different name, for example: flatplate...,then the error appears.
     If you change the name of output file to Mesh..., then the paraview can read the data.

I hope these information be useful for you!
Best regards!

**Comment by popstar0426** [comment]
Hi:
  I have found the solution.
  The error is caused by the different name of mesh file and output file.
   The name of mesh is always Mesh000....
    If you give the output file as different name, for example: flatplate...,then the error appears.
     If you change the name of output file to Mesh..., then the paraview can read the data.

I hope these information be useful for you!
Best regards!

**Comment by mlopez14** [comment]
Thanks for bringing that up! Jacob just fixed it!
