### ISSUE TITLE
The position of "send_sgsf_fpts" in the "CalcResidual" method

### ISSUE THREAD

**Issue by jmaximelv** [HiFiLES/HiFiLES-solver#86]
Hi all,
I've a question about the position of the method "send_sgsf_fpts" in the CalcResidual. In the current code, the send function appears before the method "evaluate_sgsFlux"! Why? I think it should locate between "evaluate_sgsFlux" and "receive_sgsf_fpts".

Thanks for your comments.

Best regards,
Maixme

**Comment by jrbull** [comment]
Maxime,
I think you are right - this is a bug, although it may not show up in any significant way in simulation results. Thanks for bringing this to our attention.
Regards,
Jonathan
Postdoctoral Scholar
Dept of Aero/Astro Engineering
Stanford University
