### ISSUE TITLE
Non-dimensionalization for SA model equation.

### ISSUE THREAD

**Issue by zhan1457** [HiFiLES/HiFiLES-solver#88]
Hi,

I found the code is nondimensionalized except for SA model's source term. Since you use the non-dimensional velocity to help solve the nu_tilde, does it also need to be non-dimensional?

**Comment by jewatkins** [comment]
Hi Wanjia,

nu_tilde is non-dimensionalized by the reference velocity and length. The equation solves for non-dimensional nu_tilde so if you want to know what dimensional nu_tilde is, you need to multiple by uvw_ref and L_ref.

Some of the source terms for the non-dimensional form of the equation for the SA model should include a reference Reynolds number. The non-dimensionalization of the velocity is based on a reference Reynolds number of 1 so it's not necessary to include them. Let me know if you have any more questions.

-Jerry

**Comment by zhan1457** [comment]
Thank you for your quick reply. I was misled by a paper that uses kinetic viscosity to do the non-dimensionalization.
