### ISSUE TITLE
LU-SGS temporal discretization

### ISSUE THREAD

**Issue by popstar0426** [HiFiLES/HiFiLES-solver#90]
Hi:
   Do you have any idea with implicit temporal discretization in HiFiLES?
   For example: LU-SGS? 

Best regards!
Yue

**Comment by mlopez14** [comment]
Not for now. Implicit methods, from what we have seen, take up more memory than GPUs can handle and do not scale as well in supercomputers.

Nevertheless, I'm sure there are special ways of making them more cost-effective with respect to explicit methods in vortex dominated flows.

Certainly let us know if you have found implicit methods that would scale well and be well suited to GPUs, we might give them a try!

**Comment by popstar0426** [comment]
Hi:
  I am using workstations without GPUs.
  If I would like to add Implicit temporal discretization in HiFiLES, what should I do?
  Could you give me any suggestion?

Best regards!

**Comment by mlopez14** [comment]
Here is a paper to get you started in the implementation in a code like HiFiLES (Flux Reconstruction is very similar to Spectral Difference):
dept.ku.edu/~cfdku/papers/aiaa-2007-4322.pdf

And here is a good introduction to the idea of using LU-SGS for non-linear systems (Euler equations):
aero-comlab.stanford.edu/Papers/AIAA-10007-471.pdf

**Comment by popstar0426** [comment]
Hi:
   Could you share me some papers on low-storage RK45 method?
   Where is the implementation of it (low-storage RK45 method) in the code?

Best regards!
Yue

**Comment by JacobCrabill** [comment]
Hi Yue,

We're using the 'two-register', 5-stage, 4th-order RK scheme described in the paper by Kennedy, Carpenter, and Lewis: http://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/19990064369.pdf

The implementation is found in eles::AdvanceSolution(int in_step, int adv_type).

-Jacob

**Comment by popstar0426** [comment]
Hi:
   Thank you, Jacob!

Best regards!
