### ISSUE TITLE
Velocity direction of inlet boundary

### ISSUE THREAD

**Issue by popstar0426** [HiFiLES/HiFiLES-solver#91]
Hi:
   Consider the flow around an airfoil with attack angle 8 degree, only two boundary conditions: Adiabat_Fix (wall of the airfoil) and Char (farfield) are defined.
   Question is that: How can I specify the velocity direction to simulate the 8 degree attack angle?
   I noticed the input as below:
   Viscous Boundary Conditions - Used only for viscous cases
    Mach_free_stream: Mach number of free-stream flow
    nx_free_stream: normalized x-component of free-stream flow [unit normal component]
    ny_free_stream: normalized y-component of free-stream flow
    nz_free_stream: normalized z-component of free-stream flow
   
    Does "nx_free_stream" and "ny_free_stream" define the velocity direction of the farfield?
    However, when I define the input file like this:
    -----------------------------------
Boundary conditions
-----------------------------------
==== Viscous ====
fix_vis           0                   // 0: Sutherland's law, 1: Constant viscosity
Mach_free_stream  0.1
nx_free_stream    0.99756405
ny_free_stream    0.06975647
nz_free_stream    0.
Re_free_stream    60000
L_free_stream     1.
T_free_stream     300
T_wall            300
Mach_wall         0.
nx_wall           1.
ny_wall           0.
nz_wall           0.
T_wall            300
Mach_c_ic 0.1
nx_c_ic 0.99756405
ny_c_ic 0.06975647
nz_c_ic 0.

  The attack angle is still zero. Is there any wrong?

Best regards!

**Comment by mlopez14** [comment]
No, you have the right idea. Just to make sure, what happens as ny goes higher?
Is the resulting force in the y direction zero?

**Comment by popstar0426** [comment]
Hi:
   I did not follow you!
   I attached a figure to describe my idea. nx is cos(alpha), ny is sin(alpha).

**Comment by popstar0426** [comment]
Hi:
   There is something wrong with uploading the figure.
   Could you kindly explain nx and ny again?

Best regards!

**Comment by popstar0426** [comment]
![attack](https://cloud.githubusercontent.com/assets/9553925/9560127/86392a04-4e37-11e5-97a3-c88ec925fa26.jpg)
Hi:
   I attached a figure to describe the nx and ny. 
   What do you mean "the resulting force"?

Best regards!

**Comment by popstar0426** [comment]
Hi:
   Now I understand your comments.
   I will increase ny and check it again.
