### ISSUE TITLE
some questions about using HiFiLES

### ISSUE THREAD

**Issue by hzhf** [HiFiLES/HiFiLES-solver#94]
Q1:
For viscous simulation, the size of input mesh file must be in meters, is it?
Q2:
There are no parameters about prism elements in the input control file, are prism elements supported in HiFiLES?
Q3:
As the bound condition of Supersonic inlet is used in my case, so the parameters such as rho_bound,u_bound, v_bound, w_bound and p_bound in the input control file should be set as below:
rho_bound = 1.0; u_bound = nx_free_stream; v_bound = ny_free_stream; w_bound = nz_free_stream;
p_bound = 1.0 / (gamma * Mach_free_stream  * Mach_free_stream )
is it like what i say?
Q4:
when the value of the parameter of viscous in the input control file is 1, it means laminar flow, does it?
Q5:
Could you explain all parameters in the input control file and introduce how to use them???
Could you support more tutorials, such as high mach shock-capture / shock-interfere cases, LES model cases, SA cases??? 

Thanks for your kind and help!

**Comment by mlopez14** [comment]
Your questions about the dimensions can be answered in this tutorial that I have just written, let me know if it is not clear: https://github.com/HiFiLES/HiFiLES-solver/wiki/Non-dimensionalization

The question regarding the inputs can be answered by reading the section on the input file: https://github.com/HiFiLES/HiFiLES-solver/wiki/Input-File

No, whether the solution is turbulent or laminar will depend strongly on the Reynolds number and less strongly on the geometry. Reducing viscosity while keeping the Reynolds number constant will in essence reduce the density of the flow.

The creation of the tutorials depends strongly on the availability of the team and community participation. I would encourage you to contact other users who have run a case similar to the one you would like to run. At the moment we are focusing our energy on stabilizing solutions under extreme cases of high Re and high Ma values with low mesh refinement, but that will take us some time.

For the moment we are limited to vortex-dominated, mid-range Re, Ma flows.
