### ISSUE TITLE
The choice of time step options

### ISSUE THREAD

**Issue by hzhf** [HiFiLES/HiFiLES-solver#95]
When setting dt_type = 1 (global step time), the residual results calculated on CPUs and GPUs for the same simulations are different. why is it？？？

**Comment by jewatkins** [comment]
Hi hzhf,

Thanks for your question. Unfortunately, global CFL based time stepping hasn't been implemented yet on the GPU code. If you attempt to use global CFL based time stepping on the GPU, I believe it uses the specified time step in the input file.

Also, the local time stepping implementation on the CPU is different than the one implemented on the GPU. You may run into different residuals here too.

-Jerry
