### ISSUE TITLE
 test about nasa0714

### ISSUE THREAD

**Issue by paipaizhu** [HiFiLES/HiFiLES-solver#98]
Hi:
Recently，I want to run a test, but running speed is slow,i do not know why.here is my inputfile.can you help me explain it.the amount of grid is 40000,First layer grid height is 1E-6.
----------------------------
 Solver parameters
----------------------------
// 0: Euler/Navier-Stokes, 1:Advection/Adv-Diffusion
equation  0
viscous   1

// 0: Rusanov, 1: Lax-Friedrich, 2: Roe
riemann_solve_type       0
vis_riemann_solve_type   0

// 0: Isentropic Vortex, 1: Uniform flow, 2: Sine Wave
ic_form    1

// 0: Normal (doesn't have an analytical solution), 1:Isentropic Vortex, 2: Advection-Equation
test_case  0
order      3          // Order of basis polynomials
dt_type    1          // 0: User-supplied, 1: Global, 2: Local
dt         0.0001
CFL        0.01
n_steps    100000000
adv_type   3          // 0: Forward Euler, 3: RK45
tau        1.0
pen_fact   0.5
turb_model  1

-----------------------
Mesh options
-----------------------
mesh_file  nasa0714.neu

-----------------------------------
Monitoring, plotting parameters
-----------------------------------
p_res        6            // Plotting resolution, # of nodes per direction
write_type   1            // 0: Paraview, 1: Tecplot
volume_cub_order   12     // Order of cubature rule for integrating over element volumes

monitor_res_freq   100
plot_freq          1000
data_file_name     invCyl
restart_dump_freq  100000
diagnostic_fields 6 u v w energy pressure mach
res_norm_type      1     // 1:L1 norm, 2:L2 norm, 0:infinity norm <not implemented>
error_norm_type    1     // 1:L1 norm, 2:L2 norm, 0:infinity norm <not implemented>
res_norm_field     0     // Density

------------------------
Element parameters
---------------------------
==== Tris ====
upts_type_tri      0
fpts_type_tri      0
vcjh_scheme_tri    3
c_tri              0.0
sparse_tri         0

==== Quads ====
upts_type_quad     0    // 0: Gauss, 1: Gauss-Lobatto
vcjh_scheme_quad   3    // 0: VCJH, 1: DG, 2: SD, 3: Hu, 4: c_+
eta_quad           0.0
sparse_quad        0

==== Hexs ====
upts_type_hexa     0
vcjh_scheme_hexa   0
eta_hexa           0.
sparse_hexa        0

==== Tets ====
upts_type_tet      1
fpts_type_tet      0
vcjh_scheme_tet    0
eta_tet            0.0
sparse_tet         0

==== Prisms ====
upts_type_pri_tri  0
upts_type_pri_1d   0
vcjh_scheme_pri_1d 0
eta_pri            0.0
sparse_pri         0

------------------------------------
Fluid Parameters
------------------------------------
gamma         1.4
prandtl       0.72
S_gas         120.
T_gas         291.15
R_gas         286.9
mu_gas        1.827E-05

-----------------------------------
Boundary conditions
-----------------------------------
==== Viscous ====
fix_vis           0                   // 0: Sutherland's law, 1: Constant viscosity
Mach_free_stream  0.724
nx_free_stream    1.
ny_free_stream    0.
nz_free_stream    0.
Re_free_stream    1000000.
L_free_stream     1.
T_free_stream     300 
T_wall            300
Mach_wall         0.
nx_wall           1.
ny_wall           0.
nz_wall           0.
T_wall            300

==== Inviscid ====
rho_bound         1.
u_bound           1.0
v_bound           1.0
w_bound           0.0
p_bound           17.857142857142854098

**Comment by JacobCrabill** [comment]
Hi,

Could you explain what you mean by the code running slowly so we can help you diagnose any issues you may be having?

-Jacob

**Comment by paipaizhu** [comment]
Hi Jacobraill,
I have already know why the code running is slow.as for large Re,we have to add the amount of mesh in boundary layer.then dt(dt_type=0) become smaller.I set it to 10E-9.and the Res is large.it will take lots of time to calculate.
so what i can do to derease the calculate time?
Best regards

**Comment by JacobCrabill** [comment]
HiFiLES does not have any steady-state convergence acceleration methods implemented at this time; the only change you could potentially make to your input file is to change "vcjh_scheme_*" to 4, which modifies the correction functions to David William's "C_+" scheme, which has the highest CFL limit out of all available methods.

Another thing you could do is to first run the simulation with 1st-order polynomials ("order 1"), which will allow you to generate a converged simulation much more quickly, and then restart your simulation at a higher order, using the lower-order solution as the initial condition.

Lastly, although 40,000 elements is a very large number of elements to resolve a 2D geometry, if the wall boundaries of your mesh are represented by linear elements (as opposed quadratic or higher curved triangles/quads), the sharp corners between elements can create issues that impair convergence.
